[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = '''! (has('macunix') && has('kaoriya') && isdirectory(expand('$VIM/plugins/vimproc')))'''

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'atelierbram/vim-colors_atelier-schemes'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'delphinus35/vim-colors-solarized'
rev  = 'for-hydrozen-fork'

[[plugins]]
repo = 'delphinus35/vim-emacscommandline'

[[plugins]]
repo = 'delphinus35/vim-markdown'
rev  = 'merged-inline_and_code_fixes-conceal'

[[plugins]]
repo = 'delphinus35/vim-rails'
rev  = 'feature/recognize-ridgepole'

[[plugins]]
repo = 'delphinus35/vim-unimpaired'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'elzr-vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo    = 'osyo-manga/vim-watchdogs'
depends = [
    'vim-hier',
    'quickfixstatus',
    'shabadou.vim',
    'vim-quickrun',
  ]

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'tpope/vim-capslock'

[[plugins]]
repo    = 'tpope/vim-fugitive'

[[plugins]]
repo    = 'tpope/vim-repeat'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'vim-scripts/HiColors'

[[plugins]]
repo    = 'vim-scripts/LineJuggler'
depends = [
    'vim-repeat',
    'ingo-library',
    'visualrepeat',
  ]

[[plugins]]
repo = 'applescript.vim'

[[plugins]]
repo = 'ingo-library'

[[plugins]]
repo = 'nginx.vim'

[[plugins]]
repo = 'visualrepeat'

#[[plugins]]
#repo        = 'https://raw.githubusercontent.com/tmux/tmux/master/examples/tmux.vim'
#type        = 'raw'
#script_type = 'syntax'

