# basic {{{
[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = '''! (has('macunix') && has('kaoriya') && isdirectory(expand('$VIM/plugins/vimproc')))'''
hook_post_update = 'call delphinus#init#vimproc#hook_post_update()'

[[plugins]]
repo     = 'delphinus35/vim-colors-solarized'
rev      = 'for-hydrozen-fork'
hook_add = 'let g:solarized_menu = 0'

[[plugins]]
repo = 'kana/vim-vspec'

[[plugins]]
repo = 'rkitover/vimpager'
if   = '''! has('macunix')'''

[[plugins]]
repo     = 'ryanoasis/vim-devicons'
hook_add = 'call delphinus#init#devicons#hook_add()'

[[plugins]]
repo     = 'tpope/vim-capslock'
hook_add = 'imap <C-L> <Plug>CapsLockToggle'

[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = 'call delphinus#init#fugitive#hook_add()'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo     = 'vim-airline/vim-airline'
depends  = ['vim-airline-themes']
hook_add = 'call delphinus#init#airline#hook_add()'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
# }}}

# syntax {{{
[[plugins]]
repo = 'ChrisYip/Better-CSS-Syntax-for-Vim'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'delphinus35/perl-test-base.vim'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo     = 'delphinus35/vim-markdown'
rev      = 'merged-inline_and_code_fixes-conceal'
hook_add = 'call delphinus#init#markdown#hook_add()'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo     = 'elzr/vim-json'
if       = '''! has('kaoriya')'''
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
# }}}

# filetype {{{
[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'c9s/perlomni.vim'

[[plugins]]
repo = 'delphinus35/vim-rails'
rev  = 'feature/recognize-ridgepole'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo  = 'ternjs/tern_for_vim'
build = 'npm install'
# }}}

# for unite {{{
[[plugins]]
repo      = 'Shougo/unite-outline'

[[plugins]]
repo      = 'Kocha/vim-unite-tig'

[[plugins]]
repo      = 'basyura/unite-rails'

[[plugins]]
repo      = 'lambdalisue/vim-gista-unite'
hook_add = '''
  let g:gista#default_yank_method = 'url'
  let g:gista#auto_yank_after_post = 1
'''

[[plugins]]
repo      = 'pekepeke/vim-unite-z'

[[plugins]]
repo      = 'sorah/unite-bundler'

[[plugins]]
repo      = 'tsukkee/unite-tag'

[[plugins]]
repo     = 'ujihisa/neco-look'
hook_add = 'call delphinus#init#necolook#hook_add()'
# }}}

# vim-script {{{
[[plugins]]
repo = 'HiColors'

[[plugins]]
repo = 'applescript.vim'

[[plugins]]
repo = 'ingo-library'

[[plugins]]
repo = 'nginx.vim'
# }}}

# dependencies {{{
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'
# }}}

#[[plugins]]
#repo        = 'https://raw.githubusercontent.com/tmux/tmux/master/examples/tmux.vim'
#type        = 'raw'
#script_type = 'syntax'

# vim:se fdm=marker:
