# Shougoware {{{
[[plugins]]
repo = 'Shougo/echodoc.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo    = 'Shougo/neocomplete.vim'
depends = 'echodoc.vim'
on_i    = 1
hook_source = '''
  let g:echodoc_enable_at_startup = 1
'''

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim', 'vimfiler', 'vimshell']

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/vimfiler'
on_source = 'unite.vim'
on_path   = '.*'
on_cmd    = [
    'VimFiler',
    'VimFilerExplorer',
    'Edit',
    'Read',
    'Source',
    'Write',
  ]

[[plugins]]
repo   = 'Shougo/vimshell'
on_cmd = [
    'VimShell',
    'VimShellExecute',
    'VimShellInteractive',
    'VimShellTerminal',
    'VimShellPop',
  ]

[[plugins]]
repo   = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']
# }}}

# for unite {{{
[[plugins]]
repo      = 'Kocha/vim-unite-tig'
on_source = ['unite.vim']

[[plugins]]
repo      = 'basyura/unite-rails'
on_source = ['unite.vim']

[[plugins]]
repo      = 'delphinus35/unite-ghq'
on_source = ['unite.vim']
hook_source = '''
  if exists('$H')
    let g:unite_ghq_executable = 'ghq.sh'
  endif
'''

[[plugins]]
repo        = 'fuenor/qfixhowm'
on_map      = ['g,m', 'g,c', 'g,s', 'g,q']
on_source   = ['unite.vim']
hook_source = 'call delphinus#qfixhowm#init()'

[[plugins]]
repo      = 'kannokanno/unite-dwm'
on_source = ['unite.vim']

[[plugins]]
repo      = 'lambdalisue/vim-gista-unite'
depends   = ['vim-gista']
on_source = ['unite.vim']
hook_source = '''
  let g:gista#default_yank_method = 'url'
  let g:gista#auto_yank_after_post = 1
'''

[[plugins]]
repo      = 'osyo-manga/unite-qfixhowm'
depends   = ['qfixhowm']
on_source = ['unite.vim']

[[plugins]]
repo      = 'pekepeke/vim-unite-z'
on_source = ['unite.vim']

[[plugins]]
repo      = 'sorah/unite-bundler'
on_source = ['unite.vim']

[[plugins]]
repo      = 'spolu/dwm.vim'
on_map    = ['<Plug>DWM']
on_source = ['unite.vim']

[[plugins]]
repo        = 'thinca/vim-ref'
on_cmd      = ['Ref']
on_source   = ['unite.vim']
hook_add    = 'call delphinus#ref#before_init()'
hook_source = 'call delphinus#ref#init()'

[[plugins]]
repo      = 'tsukkee/unite-tag'
depends   = ['neoinclude.vim']
on_source = ['unite.vim']
# }}}

# on_cmd {{{
[[plugins]]
repo     = 'airblade/vim-rooter'
on_cmd   = ['Rooter']
hook_add = '''
  let g:rooter_use_lcd = 1
  let g:rooter_silent_chdir = 1
  autocmd BufEnter * Rooter
'''

[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_cmd   = ['tablemode']
hook_add = '''
  nnoremap `tm :call tablemode#Toggle()<CR>
  let g:table_mode_corner='|'
'''

[[plugins]]
repo   = 'fuenor/JpFormat.vim'
on_cmd = ['JpFormatAll', 'JpJoinAll']
on_ft  = ['howm_memo']

[[plugins]]
repo   = 'gregsexton/VimCalc'
on_cmd = ['Calc']

[[plugins]]
repo   = 'kannokanno/previm'
on_cmd = ['PrevimOpen']

[[plugins]]
repo    = 'lambdalisue/vim-gista'
on_cmd  = ['Gista']
on_func = ['gista#']

[[plugins]]
repo   = 'rizzatti/dash.vim'
on_cmd = ['Dash']
gui    = 1

[[plugins]]
repo        = 'sgur/vim-lazygutter'
on_cmd      = ['GitGutterToggle']
hook_source = 'call delphinus#lazygutter#init()'

[[plugins]]
repo   = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo     = 'thinca/vim-fontzoom'
on_cmd   = ['Fontzoom']
on_map   = ['<Plug>(fontzoom-']
gui      = 1
hook_add = 'call delphinus#fontzoom#init()'

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']
on_source = ['capture.vim']

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]]
repo     = 'tyru/open-browser.vim'
on_cmd   = ['OpenBrowser', 'OpenBrowserSearch']
on_map   = ['<Plug>(openbrowser-']
hook_add = '''
  nmap g<CR> <Plug>(openbrowser-smart-search)
  vmap g<CR> <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo   = 'AnsiEsc.vim'
on_cmd = ['AnsiEsc']
# }}}

# on_ft {{{
[[plugins]]
repo        = 'Quramy/tsuquyomi'
on_ft       = ['typescript']
hook_source = 'call delphinus#tsuquyomi#init()'

[[plugins]]
repo  = 'catalinciurea/perl-nextmethod'
on_ft = ['perl']

[[plugins]]
repo  = 'csv.vim'
on_ft = ['csv']

[[plugins]]
repo    = 'delphinus35/neocomplete-json-schema'
depends = ['neocomplete.vim']
on_ft   = ['json']
on_i    = 1

[[plugins]]
repo  = 'dsawardekar/wordpress.vim'
on_ft = ['php']

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo  = 'msanders/cocoa.vim'
on_ft = ['objc']

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo    = 'rhysd/vim-textobj-ruby'
depends = ['vim-textobj-user']
on_ft   = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = [
    'lua', 'elixir', 'ruby', 'crystal', 'sh', 'zsh', 'vb', 'vbnet',
    'aspvbs', 'vim', 'c', 'cpp', 'xdefaults', 'objc', 'matlab',
  ]
# }}}

# on_map {{{
[[plugins]]
repo     = 'LeafCage/yankround.vim'
on_map   = ['<Plug>(yankround-']
hook_add = 'call delphinus#yankround#init()'

[[plugins]]
repo   = 'chikatoike/concealedyank.vim'
on_map = ['<Plug>(operator-concealedyank)']

[[plugins]]
repo     = 'delphinus35/vim-lycia'
on_map   = ['<Plug>(lycia']
hook_add = 'call delphinus#lycia#init()'

[[plugins]]
repo        = 'junegunn/vim-easy-align'
on_map      = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
hook_add    = 'call delphinus#easyalign#before_init()'
hook_source = 'call delphinus#easyalign#init()'

[[plugins]]
repo     = 't9md/vim-quickhl'
on_map   = ['<Plug>(quickhl-', '<Plug>(operator-quickhl-']
hook_add = 'call delphinus#quickhl#init()'

[[plugins]]
repo   = 't9md/vim-choosewin'
on_map = ['<Plug>(choosewin)']

[[plugins]]
repo     = 'easymotion/vim-easymotion'
on_map   = ['<Plug>(easymotion-']
hook_add = 'call delphinus#easymotion#init()'
# }}}

# others {{{
[[plugins]]
repo    = 'haya14busa/incsearch.vim'
depends = [
    'vim-easymotion'
    'incsearch-easymotion.vim'
    'incsearch-fuzzy.vim'
  ]
on_func  = ['incsearch#']
hook_add = 'call delphinus#incsearch#init()'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'ujihisa/neco-look'
depends = ['neocomplete.vim']
on_i = 1
# }}}

# on_idle {{{
[[plugins]]
repo    = 'itchyny/vim-cursorword'
on_idle = 1

[[plugins]]
repo             = 'itchyny/vim-parenmatch'
on_idle          = 1
hook_post_source = '''
  call parenmatch#highlight()
'''
# }}}

# vim:se fdm=marker:
