# basic {{{
[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
if = '''! (has('macunix') && has('kaoriya') && isdirectory(expand('$VIM/plugins/vimproc')))'''

  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'delphinus35/vim-colors-solarized'
rev  = 'for-hydrozen-fork'

[[plugins]]
repo = 'delphinus35/vim-emacscommandline'

[[plugins]]
repo = 'delphinus35/vim-unimpaired'

[[plugins]]
repo = 'kana/vim-vspec'

[[plugins]]
repo = 'rkitover/vimpager'
if   = '''! has('macunix')'''

[[plugins]]
repo     = 'ryanoasis/vim-devicons'
hook_add = 'call delphinus#devicons#init()'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'tpope/vim-capslock'

[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = 'call delphinus#fugitive#init()'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'vim-jp/vital.vim'
# }}}

# syntax {{{
[[plugins]]
repo = 'ChrisYip/Better-CSS-Syntax-for-Vim'

[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'delphinus35/perl-test-base.vim'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo     = 'delphinus35/vim-markdown'
rev      = 'merged-inline_and_code_fixes-conceal'
hook_add = 'call delphinus#markdown#init()'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
# }}}

# filetype {{{
[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'c9s/perlomni.vim'

[[plugins]]
repo = 'delphinus35/vim-rails'
rev  = 'feature/recognize-ridgepole'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo = 'ternjs/tern_for_vim'

  [plugins.build]
  others = 'npm install'
# }}}

# vim-script {{{
[[plugins]]
repo = 'HiColors'

[[plugins]]
repo    = 'LineJuggler'
depends = [
    'vim-repeat',
    'ingo-library',
    'visualrepeat',
  ]

[[plugins]]
repo = 'applescript.vim'

[[plugins]]
repo = 'ingo-library'

[[plugins]]
repo = 'nginx.vim'

[[plugins]]
repo = 'visualrepeat'
# }}}

# watchdogs {{{
[[plugins]]
repo    = 'osyo-manga/vim-watchdogs'
depends = [
  'vim-hier',
  'quickfixstatus',
  'shabadou.vim',
  'vim-quickrun',
]
hook_add         = 'call delphinus#watchdogs#init()'
hook_post_source = 'call delphinus#watchdogs#after_init()'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo     = 'thinca/vim-quickrun'
hook_add = 'call delphinus#quickrun#init()'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
# }}}

#[[plugins]]
#repo        = 'https://raw.githubusercontent.com/tmux/tmux/master/examples/tmux.vim'
#type        = 'raw'
#script_type = 'syntax'

# vim:se fdm=marker:
