# Shougoware {{{
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo      = 'Shougo/neomru.vim'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim', 'vimfiler', 'vimshell']

[[plugins]]
repo   = 'Shougo/unite.vim'
on_cmd = [
    'Unite',
    'UniteBookmarkAdd',
    'UniteClose',
    'UniteFirst',
    'UniteLast',
    'UniteNext',
    'UnitePrevious',
    'UniteResume',
    'UniteWithBufferDir',
    'UniteWithCurrentDir',
    'UniteWithCursorWord',
    'UniteWithInput',
    'UniteWithInputDirectory',
    'UniteWithProjectDir',
  ]

[[plugins]]
repo      = 'Shougo/unite-outline'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/vimfiler'
on_source = 'unite.vim'
on_path   = '.*'
on_cmd    = [
    'VimFiler',
    'VimFilerExplorer',
    'Edit',
    'Read',
    'Source',
    'Write',
  ]

[[plugins]]
repo   = 'Shougo/vimshell'
on_cmd = [
    'VimShell',
    'VimShellExecute',
    'VimShellInteractive',
    'VimShellTerminal',
    'VimShellPop',
  ]

[[plugins]]
repo   = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise']
# }}}

# for unite {{{
[[plugins]]
repo      = 'Kocha/vim-unite-tig'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'LeafCage/yankround.vim'
on_map    = ['<Plug>(yankround-']
on_source = ['unite.vim']

[[plugins]]
repo      = 'basyura/unite-rails'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'delphinus35/unite-ghq'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'fuenor/qfixhowm'
on_map    = ['g,m', 'g,c', 'g,s', 'g,q']
on_source = ['unite.vim']

[[plugins]]
repo      = 'kannokanno/unite-dwm'
depends   = ['Shougo/unite.vim', 'spolu/dwm.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'lambdalisue/vim-gista-unite'
depends   = ['lambdalisue/vim-gista', 'Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'osyo-manga/unite-qfixhowm'
depends   = ['Shougo/unite.vim', 'fuenor/qfixhowm']
on_source = ['unite.vim', 'qfixhowm']

[[plugins]]
repo      = 'pekepeke/vim-unite-z'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'sorah/unite-bundler'
depends   = ['Shougo/unite.vim']
on_source = ['unite.vim']

[[plugins]]
repo      = 'thinca/vim-ref'
depends   = ['Shougo/unite.vim']
on_cmd    = ['Ref']
on_source = ['unite.vim']

[[plugins]]
repo      = 'tsukkee/unite-tag'
depends   = ['Shougo/unite.vim', 'Shougo/neoinclude.vim']
on_source = ['unite.vim']
# }}}

# on_cmd {{{
[[plugins]]
repo   = 'airblade/vim-rooter'
on_cmd = ['Rooter']

[[plugins]]
repo   = 'fuenor/JpFormat.vim'
on_cmd = ['JpFormatAll', 'JpJoinAll']
on_ft  = ['howm_memo']

[[plugins]]
repo   = 'gregsexton/VimCalc'
on_cmd = ['Calc']

[[plugins]]
repo   = 'kannokanno/previm'
on_cmd = ['PrevimOpen']

[[plugins]]
repo    = 'lambdalisue/vim-gista'
on_cmd  = ['Gista']
on_func = ['gista#']

[[plugins]]
repo   = 'rizzatti/dash.vim'
on_cmd = ['Dash']
gui    = 1

[[plugins]]
repo   = 'sgur/vim-lazygutter'
on_cmd = ['GitGutterToggle']

[[plugins]]
repo   = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo   = 'thinca/vim-fontzoom'
on_cmd = ['Fontzoom']
on_map = ['<Plug>(fontzoom-']
gui    = 1

[[plugins]]
repo   = 'thinca/vim-prettyprint'
on_cmd = ['Capture', 'PP', 'PrettyPrint']

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_cmd = ['OpenBrowser', 'OpenBrowserSearch']
on_map = ['<Plug>(openbrowser-']

[[plugins]]
repo   = 'vim-scripts/AnsiEsc.vim'
on_cmd = ['AnsiEsc']
# }}}

# on_ft {{{
[[plugins]]
repo  = 'ChrisYip/Better-CSS-Syntax-for-Vim'
on_ft = ['css']

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo  = 'c9s/perlomni.vim'
on_ft = ['perl']

[[plugins]]
repo  = 'catalinciurea/perl-nextmethod'
on_ft = ['perl']

[[plugins]]
repo  = 'csv.vim'
on_ft = ['csv']

[[plugins]]
repo  = 'delphinus35/perl-test-base.vim'
on_ft = ['perl']

[[plugins]]
repo  = 'aklt/plantuml-syntax'
on_ft = ['markdown', 'plantuml']

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = [
    'css',  'html', 'less',   'lua', 'moon',
    'sass', 'scss', 'stylus', 'vim', 'plantuml',
  ]

[[plugins]]
repo    = 'delphinus35/neocomplete-json-schema'
depends = ['Shougo/neocomplete.vim']
on_ft   = ['json']
on_i    = 1

[[plugins]]
repo  = 'dsawardekar/wordpress.vim'
on_ft = ['php']

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo  = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript']

[[plugins]]
repo  = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo  = 'kana/vim-vspec'
on_ft = ['vim']

[[plugins]]
repo  = 'msanders/cocoa.vim'
on_ft = ['objc']

[[plugins]]
repo    = 'rhysd/vim-textobj-ruby'
depends = ['kana/vim-textobj-user']
on_ft   = ['ruby']

[[plugins]]
repo    = 'supermomonga/neocomplete-rsense.vim'
depends = ['Shougo/neocomplete.vim']
on_ft   = ['ruby']
on_i    = 1

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = [
    'lua', 'elixir', 'ruby', 'crystal', 'sh', 'zsh', 'vb', 'vbnet',
    'aspvbs', 'vim', 'c', 'cpp', 'xdefaults', 'objc', 'matlab',
  ]

[[plugins]]
repo  = 'vim-perl/vim-perl'
on_ft = ['perl']
# }}}

# on_map {{{
[[plugins]]
repo   = 'chikatoike/concealedyank.vim'
on_map = ['<Plug>(operator-concealedyank)']

[[plugins]]
repo   = 'delphinus35/vim-lycia'
on_map = ['<Plug>(lycia']

[[plugins]]
repo   = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']

[[plugins]]
repo   = 'spolu/dwm.vim'
on_map = ['<Plug>DWM']

[[plugins]]
repo   = 't9md/vim-quickhl'
on_map = ['<Plug>(quickhl-', '<Plug>(operator-quickhl-']

[[plugins]]
repo   = 't9md/vim-choosewin'
on_map = ['<Plug>(choosewin)']

[[plugins]]
repo   = 'easymotion/vim-easymotion'
on_map = ['<Plug>(easymotion-']
# }}}

# others {{{
[[plugins]]
repo = 'haya14busa/incsearch.vim'
depends = [
    'easymotion/vim-easymotion'
    'haya14busa/incsearch-easymotion.vim'
    'haya14busa/incsearch-fuzzy.vim'
  ]
on_func = ['incsearch#']

[[plugins]]
repo = 'rkitover/vimpager'

[[plugins]]
repo = 'ujihisa/neco-look'
depends = ['Shougo/neocomplete.vim']
on_i = 1

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
# }}}

# vim:se fdm=marker:
