[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'atelierbram/vim-colors_atelier-schemes'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

[[plugins]]
repo = 'delphinus35/vim-colors-solarized'
rev  = 'for-hydrozen-fork'

[[plugins]]
repo = 'delphinus35/vim-emacscommandline'

[[plugins]]
repo = 'delphinus35/vim-markdown'
rev  = 'merged-inline_and_code_fixes-conceal'

[[plugins]]
repo = 'delphinus35/vim-rails'
rev  = 'feature/recognize-ridgepole'

[[plugins]]
repo = 'delphinus35/vim-unimpaired'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

[[plugins]]
repo    = 'osyo-manga/vim-watchdogs'
depends = [
    'cohama/vim-hier',
    'dannyob/quickfixstatus',
    'osyo-manga/shabadou.vim',
    'thinca/vim-quickrun',
  ]

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'tpope/vim-capslock'

[[plugins]]
repo    = 'tpope/vim-fugitive'
augroup = 'fugitive'

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline/vim-airline-themes']

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'vim-scripts/HiColors'

[[plugins]]
repo    = 'vim-scripts/LineJuggler'
depends = [
    'tpope/vim-repeat',
    'vim-scripts/ingo-library',
    'vim-scripts/visualrepeat',
  ]

[[plugins]]
repo = 'vim-scripts/applescript.vim'

[[plugins]]
repo = 'vim-scripts/nginx.vim'

[[plugins]]
repo        = 'https://raw.githubusercontent.com/tmux/tmux/master/examples/tmux.vim'
type        = 'raw'
script_type = 'syntax'
