# Shougoware {{{
[[plugins]]
repo        = 'Shougo/echodoc.vim'
hook_source = 'let g:echodoc_enable_at_startup = 1'

[[plugins]]
repo      = 'Shougo/neoinclude.vim'
depends   = ['neoinclude.vim']
on_source = ['unite.vim']

[[plugins]]
repo        = 'Shougo/neocomplete.vim'
depends     = 'echodoc.vim'
on_i        = 1
hook_source = 'call delphinus#init#neocomplete#hook_source()'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['denite.nvim']

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim', 'vimfiler']

[[plugins]]
repo     = 'Shougo/unite.vim'
on_cmd   = ['Unite', 'UniteWithBufferDir', 'UniteWithCursorWord']
hook_add = '''"{{{
"  noremap zd :Unite dwm<CR>
"  noremap zD :Unite dein/log<CR>
"  noremap zf :Unite qfixhowm/new qfixhowm<CR>
"  noremap zF :Unite qfixhowm/new qfixhowm:nocache<CR>
"  noremap zg :Unite file_rec/async<CR>
"  noremap zG :Unite grep:.<CR>
"  "noremap <c-]> :UniteWithCursorWord -immediately tag/include<CR>
"  noremap zi :Unite tig<CR>
"  noremap zI :Unite gista<CR>
"  noremap zl :Unite outline<CR>
"  noremap zL :Unite decls<CR>
"  noremap zn :UniteWithBufferDir -buffer-name=files file file/new<CR>
"  noremap zu :Unite bundler<CR>
"  noremap zU :UniteResume<CR>
"  noremap zT :Unite tab<CR>
"  noremap zN :Unite -buffer-name=files file file/new<CR>
"  noremap zp :Unite dwm buffer_tab file_mru:long<CR>
"  noremap zP :Unite yankround<CR>
"  noremap zh :Unite ghq<CR>
"  noremap ZB :Unite rails/bundle<CR>
"  noremap ZC :Unite rails/controller<CR>
"  noremap ZD :Unite rails/db<CR>
"  noremap ZG :Unite rails/bundled_gem<CR>
"  noremap ZH :Unite rails/helper<CR>
"  noremap ZJ :Unite rails/javascript<CR>
"  noremap ZL :Unite rails/lib<CR>
"  noremap ZM :Unite rails/model<CR>
"  noremap ZO :Unite rails/command<CR>
"  noremap ZR :Unite rails/route<CR>
"  noremap ZS :Unite rails/spec<CR>
"  noremap ZT :Unite tsproject<CR>
"  noremap ZV :Unite rails/view<CR>
"  noremap Zc :Unite rails/config<CR>
"  noremap Zj :Unite rails/json_schema<CR>
"  noremap Zl :Unite rails/log<CR>
"  noremap Zm :Unite rails/mailer<CR>
"  noremap Zr :Unite rails/root<CR>
"  noremap Zs :Unite rails/stylesheet<CR>
"}}}'''
hook_source = 'call delphinus#init#unite#hook_source()'

[[plugins]]
repo      = 'Jagua/vim-denite-ghq'
on_source = ['denite.nvim']

[[plugins]]
repo    = 'Shougo/denite.nvim'
on_cmd  = ['Denite', 'DeniteBufferDir', 'DeniteCursorWord']
on_func = ['denite#']
depends = ['unite.vim', 'vim-denite-ghq']
hook_add = '''"{{{
  noremap zn :<C-u>DeniteBufferDir file file:new<CR>
  noremap zN :<C-u>Denite file<CR>
  noremap zl :<C-u>Denite outline<CR>
  noremap zL :<C-u>Denite decls<CR>
  noremap za :<C-u>Denite my_file_rec<CR>
  noremap zg :<C-u>Denite grep<CR>
  noremap z/ :<C-u>DeniteCursorWord grep:.<CR>
  noremap zd :<C-u>Denite dein<CR>
  noremap zD :<C-u>Denite unite:dein/log<CR>
  noremap zp :<C-u>Denite buffer my_file_mru<CR>
  noremap zh :<C-u>Denite ghq<CR>
  noremap zm :<C-u>Denite memo memo:new<CR>
  noremap zU :<C-u>Denite -resume<CR>
  noremap zj :<C-u>Denite -resume -cursor-pos=+1 -immediately<CR>
  noremap zk :<C-u>Denite -resume -cursor-pos=-1 -immediately<CR>
"}}}'''
hook_source = 'call delphinus#init#denite#hook_source()'

[[plugins]]
repo      = 'Shougo/vimfiler'
on_source = ['unite.vim']
on_cmd    = [
  'VimFiler',
  'VimFilerExplorer',
  'Edit',
  'Read',
  'Source',
  'Write',
]
hook_add         = 'nnoremap `f :VimFilerBufferDir<CR>'
hook_source      = 'call delphinus#init#vimfiler#hook_source()'
hook_post_source = 'call delphinus#init#vimfiler#hook_post_source()'
# }}}

# for unite {{{
[[plugins]]
repo      = 'delphinus/unite-ghq'
on_source = ['unite.vim']
hook_source = '''
  if exists($H) && $H != $HOME
    let g:unite_ghq_executable = 'ghq.sh'
  endif
'''

[[plugins]]
repo        = 'fuenor/qfixhowm'
on_map      = ['g,m', 'g,c', 'g,s', 'g,q']
on_source   = ['unite.vim']
hook_source = 'call delphinus#init#qfixhowm#hook_source()'

[[plugins]]
repo      = 'osyo-manga/unite-qfixhowm'
depends   = ['qfixhowm']
on_source = ['unite.vim']

[[plugins]]
repo      = 'delphinus/dwm.vim'
rev       = 'feature/disable-in-denite'
on_map    = ['<Plug>DWM']
on_source = ['unite.vim']
hook_add  = '''"{{{
  let g:delphinus#dwm#min_master_pane_width = get(g:, 'delphinus#dwm#min_master_pane_width', 86)

  let s:toggle_set_master_pane_width = 0

  let g:dwm_map_keys = 0
  nnoremap <C-J> <C-W>w
  nnoremap <C-K> <C-W>W
  nmap <C-S> <Plug>DWMRotateClockwise
  nmap <C-Q> <Plug>DWMRotateCounterclockwise
  nmap <C-N> <Plug>DWMNew
  nmap <C-C> <Plug>DWMClose
  nmap <C-Space> <Plug>DWMFocus
  nmap <C-L> <Plug>DWMGrowMaster

  command! DWMSetMasterPaneWidth call delphinus#dwm#set_master_pane_width()
  command! DWMDisable call delphinus#dwm#disable()
  command! DWMEnable call delphinus#dwm#enable()
"}}}'''

[[plugins]]
repo        = 'thinca/vim-ref'
on_cmd      = ['Ref']
on_source   = ['unite.vim']
hook_add    = '''"{{{
  noremap `rm :Unite ref/man<CR>
  noremap `rp :Unite ref/perldoc<CR>
  noremap `rr :Unite ref/refe<CR>
"}}}'''
hook_source = 'call delphinus#init#ref#hook_source()'
# }}}

# on_cmd {{{
[[plugins]]
repo   = 'fuenor/JpFormat.vim'
on_cmd = ['JpFormatAll', 'JpJoinAll']
on_ft  = ['howm_memo']

[[plugins]]
repo     = 'lambdalisue/vim-gista'
on_cmd   = ['Gista']
on_func  = ['gista#']
hook_add = '''
  let g:gista#command#list#enable_default_mappings = 0
  nnoremap gl :<c-u>Gista list<CR>
  nnoremap gL :<c-u>Gista list 
'''
hook_post_source = 'call delphinus#init#gista#hook_post_source()'

[[plugins]]
repo = 'lambdalisue/neovim-prompt'

[[plugins]]
repo     = 'lambdalisue/lista.nvim'
depends  = ['vim-rplugin', 'neovim-prompt']
on_cmd   = ['Lista', 'ListaCursorWord']
hook_source = '''
  let g:lista#custom_mappings = [
    \ ['<C-D>', '<Del>'],
    \ ['<C-A>', '<Home>'],
    \ ['<C-E>', '<End>'],
    \ ['<C-F>', '<Right>'],
    \ ['<C-B>', '<Left>'],
    \ ['<C-K>', '<lista:select_previous_candidate>'],
    \ ['<C-J>', '<lista:select_next_candidate>'],
    \ ['<C-C>', '<Esc>'],
    \]
'''
hook_add = '''
  nnoremap # :<C-u>Lista<CR>
  nnoremap g# :<C-u>ListaCursorWord<CR>
'''

[[plugins]]
repo = 'lambdalisue/vim-rplugin'

[[plugins]]
repo   = 'powerman/vim-plugin-AnsiEsc'
on_cmd = ['AnsiEsc']

[[plugins]]
repo   = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo        = 'thinca/vim-fontzoom'
on_cmd      = ['Fontzoom']
on_map      = ['<Plug>(fontzoom-']
if          = '''has('gui')'''
hook_add    = '''"{{{
  nmap <unique> <silent> + <Plug>(fontzoom-larger)
  nmap <unique> <silent> - <Plug>(fontzoom-smaller)
  nmap <unique> <silent> <C-ScrollWheelUp> <Plug>(fontzoom-larger)
  nmap <unique> <silent> <C-ScrollWheelDown> <Plug>(fontzoom-smaller)
"}}}'''
hook_source = '''"{{{
  let g:fontzoom_no_default_key_mappings=1
"}}}'''

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']
on_source = ['capture.vim']

[[plugins]]
repo     = 'thinca/vim-quickrun'
on_cmd   = ['QuickRun']
hook_add = '''"{{{
  let g:quickrun_no_default_key_mappings=1

  for [s:key, s:com] in items({
        \ 'x': '>message',
        \ 's': '-runner shell',
        \ 'w': '-runner vimproc >buffer',
        \ 'q': '-runner vimproc >>buffer',
        \ })
    execute 'nnoremap <silent>' '`q' . s:key ':QuickRun' s:com '-mode n<CR>'
    execute 'vnoremap <silent>' '`q' . s:key ':QuickRun' s:com '-mode v<CR>'
  endfor
"}}}'''

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]]
repo     = 'tyru/open-browser.vim'
on_cmd   = ['OpenBrowser', 'OpenBrowserSearch']
on_func  = ['openbrowser#open']
on_map   = ['<Plug>(openbrowser-']
hook_add = '''
  nmap g<CR> <Plug>(openbrowser-smart-search)
  vmap g<CR> <Plug>(openbrowser-smart-search)
'''
# }}}

# on_ft {{{
[[plugins]]
repo        = 'Quramy/tsuquyomi'
on_ft       = ['typescript']
build       = 'npm install'
hook_source = '''
  let g:tsuquyomi_disable_default_mappings = 1
  let g:tsuquyomi_use_dev_node_module = 1
  let g:tsuquyomi_definition_split = 1
  let g:tsuquyomi_completion_detail = 1

  augroup TsuquyomiMappings
    autocmd!
    autocmd FileType typescript map <buffer> <C-]> <Plug>(TsuquyomiDefinition)
    autocmd FileType typescript map <buffer> <C-@> <Plug>(TsuquyomiReferences)
    autocmd FileType typescript nnoremap <buffer> <silent> K :<c-u>echo tsuquyomi#hint()<CR>
    autocmd FileType typescript map <buffer> gK <Plug>(TsuquyomiSignatureHelp)
  augroup END
'''

[[plugins]]
repo  = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo  = 'machakann/vim-Verdin'
on_ft = ['vim']

[[plugins]]
repo    = 'delphinus/neocomplete-json-schema'
depends = ['neocomplete.vim']
on_ft   = ['json']
on_i    = 1

[[plugins]]
repo  = 'dsawardekar/wordpress.vim'
on_ft = ['php']

[[plugins]]
repo        = 'fatih/vim-go'
on_ft       = ['go']
hook_source = '''
  let g:go_addtags_transform = 'camelcase'
  let g:go_auto_sameids = 0
  let g:go_auto_type_info = 0
  let g:go_autodetect_gopath = 0
  let g:go_def_mapping_enabled = 0
  let g:go_def_mode = 'godef'
  let g:go_fmt_command = 'goimports'
  let g:go_fmt_experimental = 1
  let g:go_gocode_unimported_packages = 1
  let g:go_highlight_array_whitespace_error = 1
  let g:go_highlight_build_constraints = 1
  let g:go_highlight_chan_whitespace_error = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_generate_tags = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_space_tab_error = 1
  let g:go_highlight_types = 1
  let g:go_info_mode = 'gocode'
  let g:go_metalinter_autosave = 1
  let g:go_metalinter_autosave_enabled = ['vet', 'golint']
  let g:go_metalinter_deadline = '10s'
  let g:go_template_use_pkg = 1
'''

[[plugins]]
repo  = 'msanders/cocoa.vim'
on_ft = ['objc']

[[plugins]]
repo    = 'rhysd/vim-textobj-ruby'
depends = ['vim-textobj-user']
on_ft   = ['ruby']

[[plugins]]
repo  = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = [
    'lua', 'elixir', 'ruby', 'crystal', 'sh', 'zsh', 'vb', 'vbnet',
    'aspvbs', 'vim', 'c', 'cpp', 'xdefaults', 'objc', 'matlab',
  ]
# }}}

# on_map {{{
[[plugins]]
repo     = 'LeafCage/yankround.vim'
on_map   = ['<Plug>(yankround-']
hook_add = '''"{{{
  nmap p <Plug>(yankround-p)
  xmap p <Plug>(yankround-p)
  nmap P <Plug>(yankround-P)
  nmap gp <Plug>(yankround-gp)
  xmap gp <Plug>(yankround-gp)
  nmap gP <Plug>(yankround-gP)
  nmap <c-p> <Plug>(yankround-prev)
  nmap <expr><c-n> yankround#is_active() ? "\<Plug>(yankround-next)" : "\<Plug>DWMNew"
"}}}'''

[[plugins]]
repo     = 'arecarn/vim-fold-cycle'
on_map   = ['<Plug>(fold-cycle-']
hook_add = '''"{{{
  nmap <CR> <Plug>(fold-cycle-open)
  nmap <BS> <Plug>(fold-cycle-close)
  nmap <C-h> <Plug>(fold-cycle-close)
"}}}'''

[[plugins]]
repo     = 'chikatoike/concealedyank.vim'
on_map   = ['<Plug>(operator-concealedyank)']
hook_add = 'xmap Y <Plug>(operator-concealedyank)'

[[plugins]]
repo     = 'delphinus/vim-lycia'
on_map   = ['<Plug>(lycia']
hook_add = '''"{{{
  nmap go <Plug>(lycia)
  vmap go <Plug>(lycia)
  nmap gb <Plug>(lycia-current-branch)
  vmap gb <Plug>(lycia-current-branch)
  nmap gc <Plug>(lycia-current-commit)
  vmap gc <Plug>(lycia-current-commit)
  nmap g<C-t> <Plug>(lycia-top-page)
  nmap g<C-y> <Plug>(lycia-top-page-current-branch)
  let g:lycia_map=0
"}}}'''

[[plugins]]
repo     = 'iamcco/markdown-preview.vim'
on_map   = ['<Plug>MarkdownPreview', '<Plug>StopMarkdownPreview']
hook_add = '''
  augroup MapMarkdownPreview
    autocmd!
    autocmd FileType markdown nmap <buffer> <A-m> <Plug>MarkdownPreview
    autocmd FileType markdown nmap <buffer> <A-M> <Plug>StopMarkdownPreview
  augroup END
'''
hook_source = '''
  let g:mkdp_path_to_chrome = 'open -a Safari'
'''

[[plugins]]
repo        = 'junegunn/vim-easy-align'
on_map      = ['<Plug>(EasyAlign)', '<Plug>(LiveEasyAlign)']
hook_add    = '''"{{{
  vmap <Enter>           <Plug>(EasyAlign)
  nmap <Leader>a         <Plug>(EasyAlign)
  vmap <Leader><Enter>   <Plug>(LiveEasyAlign)
  nmap <Leader><Leader>a <Plug>(LiveEasyAlign)
"}}}'''
hook_source = 'call delphinus#init#easyalign#hook_source()'

[[plugins]]
repo     = 't9md/vim-quickhl'
on_map   = ['<Plug>(quickhl-', '<Plug>(operator-quickhl-']
hook_add = '''"{{{
  nmap <Space>m <Plug>(quickhl-manual-this)
  xmap <Space>m <Plug>(quickhl-manual-this)
  nmap <Space>t <Plug>(quickhl-manual-toggle)
  xmap <Space>t <Plug>(quickhl-manual-toggle)
  nmap <Space>M <Plug>(quickhl-manual-reset)
  xmap <Space>M <Plug>(quickhl-manual-reset)
  nmap <Space>j <Plug>(quickhl-cword-toggle)
  nmap <Space>] <Plug>(quickhl-tag-toggle)
  map  <Space>H <Plug>(operator-quickhl-manual-this-motion)
"}}}'''

[[plugins]]
repo     = 't9md/vim-choosewin'
on_map   = ['<Plug>(choosewin)']
hook_add = '''
  nmap \ <Plug>(choosewin)
  let g:choosewin_statusline_replace=0
  let g:choosewin_overlay_enable=1
'''

[[plugins]]
repo        = 'easymotion/vim-easymotion'
on_map      = ['<Plug>(easymotion-']
hook_add    = '''"{{{
  map ' <Plug>(easymotion-prefix)
  nmap s <Plug>(easymotion-overwin-f2)
  xmap s <Plug>(easymotion-s2)
  omap s <Plug>(easymotion-s2)
  nmap 'f <Plug>(easymotion-fl)
  xmap 'f <Plug>(easymotion-fl)
  omap 'f <Plug>(easymotion-fl)
  nmap 'F <Plug>(easymotion-Fl)
  xmap 'F <Plug>(easymotion-Fl)
  omap 'F <Plug>(easymotion-Fl)
  map  '/ <Plug>(easymotion-sn)
  omap '/ <Plug>(easymotion-tn)
  map  'n <Plug>(easymotion-next)
  map  'N <Plug>(easymotion-prev)
  map  'L <Plug>(easymotion-bd-jk)
  nmap 'L <Plug>(easymotion-overwin-line)
"}}}'''
hook_source = 'call delphinus#init#easymotion#hook_source()'

[[plugins]]
repo    = 'vim-scripts/LineJuggler'
depends = [
  'vim-repeat',
  'ingo-library',
  'visualrepeat',
]
on_map   = ['<Plug>(LineJuggler']
hook_add = '''"{{{
  xmap [d       <Plug>(LineJugglerDupOverUp)
  nmap [d       <Plug>(LineJugglerDupOverUp)
  xmap [E       <Plug>(LineJugglerSwapUp)
  nmap [E       <Plug>(LineJugglerSwapUp)
  xmap [e       <Plug>(LineJugglerMoveUp)
  nmap [e       <Plug>(LineJugglerMoveUp)
  xmap [<Space> <Plug>(LineJugglerBlankUp)
  nmap [<Space> <Plug>(LineJugglerBlankUp)
  xmap ]d       <Plug>(LineJugglerDupOverDown)
  nmap ]d       <Plug>(LineJugglerDupOverDown)
  xmap ]E       <Plug>(LineJugglerSwapDown)
  nmap ]E       <Plug>(LineJugglerSwapDown)
  xmap ]e       <Plug>(LineJugglerMoveDown)
  nmap ]e       <Plug>(LineJugglerMoveDown)
  xmap ]<Space> <Plug>(LineJugglerBlankDown)
  nmap ]<Space> <Plug>(LineJugglerBlankDown)
"}}}'''
# }}}

# on_event {{{
[[plugins]]
repo     = 'Chiel92/vim-autoformat'
on_event = ['FocusLost', 'CursorHold']
hook_source = '''"{{{
  augroup VimAutoformat
    autocmd!
    autocmd BufWrite *.ts :Autoformat
    autocmd BufWrite *.js :Autoformat
    autocmd BufWrite *.json :Autoformat
  augroup END
"}}}'''

[[plugins]]
repo             = 'airblade/vim-gitgutter'
on_event         = ['FocusLost', 'CursorHold']
hook_source      = 'call delphinus#init#gitgutter#hook_source()'
hook_post_source = 'call delphinus#init#gitgutter#hook_post_source()'

[[plugins]]
repo     = 'delphinus/vim-emacscommandline'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo     = 'delphinus/vim-unimpaired'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo     = 'itchyny/vim-cursorword'
on_event = ['FocusLost', 'CursorHold']

[[plugins]]
repo             = 'itchyny/vim-parenmatch'
on_event         = ['FocusLost', 'CursorHold']
hook_add         = 'let g:loaded_matchparen = 1'
hook_post_source = 'call parenmatch#highlight()'

[[plugins]]
repo     = 'thinca/vim-visualstar'
on_event = ['FocusLost', 'CursorHold']
# }}}

# others {{{
[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_func  = ['tablemode#Toggle']
hook_add = '''
  nnoremap `tm :call tablemode#Toggle()<CR>
  let g:table_mode_corner='|'
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
on_func = ['vital#of']

[[plugins]]
repo = 'vim-scripts/visualrepeat'
# }}}

# vim:se fdm=marker:
