[[plugins]]
repo = 'rkitover/vimpager'

[[plugins]]
repo = 'delphinus35/vim-colors-solarized'
rev  = 'for-hydrozen-fork'

[[plugins]]
repo = 'delphinus35/vim-emacscommandline'

[[plugins]]
repo = 'delphinus35/vim-rails'
rev  = 'feature/recognize-ridgepole'
