# basic {{{
[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'call delphinus#init#vimproc#hook_post_update()'

[[plugins]]
repo     = 'airblade/vim-rooter'
hook_add = '''
  let g:rooter_use_lcd = 1
  let g:rooter_silent_chdir = 1
'''

[[plugins]]
repo     = 'kana/vim-submode'
hook_add = '''"{{{
  call submode#enter_with('DWM_size', 'n', '', '<C-w>>', ':call DWM_GrowMaster()<CR>')
  call submode#enter_with('DWM_size', 'n', '', '<C-w><', ':call DWM_ShrinkMaster()<CR>')
  call submode#map('DWM_size', 'n', '', '>', ':call DWM_GrowMaster()<CR>')
  call submode#map('DWM_size', 'n', '', '<', ':call DWM_ShrinkMaster()<CR>')
"}}}'''

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo     = 'ryanoasis/vim-devicons'
hook_add = '''"{{{
  let g:webdevicons_enable_unite = 0
  let g:webdevicons_enable_nerdtree = 0
  let g:WebDevIconsUnicodeByteOrderMarkerDefaultSymbol = ''
  let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
  let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {
        \ 'fcgi':     '',
        \ 'perl':     '',
        \ 'sqlite':   '',
        \ 'tt':       '',
        \ 'txt':      '',
        \ }
"}}}'''

[[plugins]]
repo     = 'tmux-plugins/vim-tmux-focus-events'
if       = '''exists('$TMUX') || ! has('gui_running')'''
hook_add = 'set autoread'

[[plugins]]
repo     = 'tpope/vim-fugitive'
hook_add = '''"{{{
  let g:fugitive_git_executable = expand('HOME=$H git my-alias')
  nnoremap git :<c-u>Git
  nnoremap g<space> :<c-u>Git 
  nnoremap d< :diffget //2<CR>
  nnoremap d> :diffget //3<CR>
"}}}'''

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
# }}}

# colorscheme {{{
[[plugins]]
repo     = 'lifepillar/vim-solarized8'
on_if    = '''has('termguicolors')'''
hook_add = '''
  let g:solarized_diffmode = 'normal'
  let g:solarized_visibility = 'normal'
  if $TERM =~# 'italic'
    let g:solarized_term_italics = 1
  endif

  command! ColorschemeToggle :call delphinus#colorscheme#toggle()
'''

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:nord_italic_comments = 1
  let g:nord_comment_brightness = 20
'''
# }}}

# syntax {{{
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'

[[plugins]]
repo = 'aklt/plantuml-syntax'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo   = 'leafgarland/typescript-vim'
merged = 0

[[plugins]]
repo     = 'delphinus/vim-markdown'
rev      = 'merged-inline_and_code_fixes-conceal'
hook_add = '''"{{{
  augroup SetMarkdown
    autocmd!
    autocmd FileType markdown,howm_memo.markdown setlocal conceallevel=2
    autocmd FileType markdown,howm_memo.markdown hi markdownH1 cterm=bold,italic gui=bold,italic
    autocmd FileType markdown,howm_memo.markdown hi markdownH2 cterm=bold gui=bold
    autocmd FileType markdown,howm_memo.markdown hi markdownH3 cterm=italic gui=italic
  augroup END

  let g:markdown_fenced_languages = [
        \ 'coffee',
        \ 'cpp',
        \ 'css',
        \ 'diff',
        \ 'erlang',
        \ 'go',
        \ 'haskell',
        \ 'html',
        \ 'java',
        \ 'javascript',
        \ 'json',
        \ 'lua',
        \ 'ocaml',
        \ 'perl',
        \ 'plantuml',
        \ 'python',
        \ 'ruby',
        \ 'sh',
        \ 'sql',
        \ 'toml',
        \ 'typescript',
        \ 'vim',
        \ 'xml',
        \ ]
  " set conceal feature: default value '#*dlaibBces'
  let g:markdown_conceal = '*dlaibBes'
"}}}'''

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo     = 'elzr/vim-json'
if       = '''! has('kaoriya')'''
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'motemen/xslate-vim'

[[plugins]]
repo = 'moznion/vim-cpanfile'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'
# }}}

# filetype {{{
[[plugins]]
repo   = 'ap/vim-css-color'
merged = 0

[[plugins]]
repo = 'c9s/perlomni.vim'

[[plugins]]
repo = 'delphinus/vim-rails'
rev  = 'feature/recognize-ridgepole'

[[plugins]]
repo = 'jason0x43/vim-js-indent'

[[plugins]]
repo  = 'pearofducks/ansible-vim'

[[plugins]]
repo = 'taskwarrior/task'
rtp  = 'scripts/vim'

[[plugins]]
repo  = 'ternjs/tern_for_vim'
build = 'npm install'

[[plugins]]
repo = 'tmux-plugins/vim-tmux'
# }}}

# for unite {{{
[[plugins]]
repo = 'Jagua/vim-denite-ghq'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['unite.vim', 'vim-denite-ghq']
hook_add = '''
  noremap zn :<C-u>DeniteBufferDir file file:new<CR>
  noremap zN :<C-u>Denite file<CR>
  noremap zl :<C-u>Denite outline<CR>
  noremap zL :<C-u>Denite unite:decls<CR>
  noremap zg :<C-u>Denite file_rec<CR>
  noremap zG :<C-u>Denite grep:.<CR>
  noremap zD :<C-u>Denite unite:dein/log<CR>
  noremap zp :<C-u>Denite unite:dwm buffer file_mru<CR>
  noremap zh :<C-u>Denite ghq<CR>
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>')
  call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
  call denite#custom#map('insert', '<C-u>', '../', 'noremap')
  call denite#custom#source('_', 'matchers', ['matcher_substring'])
  " Ripgrep command on grep source
  call denite#custom#var('grep', 'command', ['rg'])
  call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#option('default', 'prompt', '❯❯❯')
  call denite#custom#option('default', 'statusline', v:false)
  " ref. https://github.com/arcticicestudio/nord-vim/issues/79
  call denite#custom#option('default', 'highlight_matched_char', 'Underlined')
  function! s:dwm_new(context)
    call DWM_New()
    call denite#do_action(a:context, 'open', a:context['targets'])
  endfunction
  call denite#custom#action('file', 'dwm_new', function('s:dwm_new'))
  call denite#custom#action('buffer', 'dwm_new', function('s:dwm_new'))
  call denite#custom#map('insert', '<C-n>', '<denite:do_action:dwm_new>')
'''

[[plugins]]
repo      = 'Shougo/neomru.vim'

[[plugins]]
repo      = 'Shougo/unite-outline'

[[plugins]]
repo      = 'Kocha/vim-unite-tig'

[[plugins]]
repo      = 'basyura/unite-rails'

[[plugins]]
repo      = 'lambdalisue/vim-gista-unite'
hook_post_source = '''
  call unite#custom#default_action('gista', 'narrow')
'''

[[plugins]]
repo      = 'pekepeke/vim-unite-z'

[[plugins]]
repo      = 'sorah/unite-bundler'

[[plugins]]
repo      = 'tsukkee/unite-tag'

[[plugins]]
repo     = 'ujihisa/neco-look'
hook_add = '''"{{{
  let g:neocomplete#text_mode_filetypes = {
        \ 'rst': 1,
        \ 'markdown': 1,
        \ 'howm_memo': 1,
        \ 'howm_memo.markdown': 1,
        \ 'gitrebase': 1,
        \ 'gitcommit': 1,
        \ 'vcs-commit': 1,
        \ 'hybrid': 1,
        \ 'text': 1,
        \ 'help': 1,
        \ 'tex': 1,
        \ }
"}}}'''
# }}}

# for lightline {{{
[[plugins]]
repo     = 'delphinus/lightline-delphinus'
rev      = 'feature/denite'
depends  = [ 'lightline', 'ale' ]
hook_add = '''
  let g:lightline_delphinus_use_powerline_glyphs = 1
  let g:lightline_delphinus_use_nerd_fonts_glyphs = 1
  let g:lightline_delphinus_colorscheme = 'nord_improved'
'''

[[plugins]]
repo    = 'itchyny/lightline.vim'

[[plugins]]
repo     = 'w0rp/ale'
hook_add = '''
  let g:ale_echo_msg_format = '%severity%: %linter%: %s'
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = ' '
  let g:ale_sign_warning = ' '
  let g:ale_statusline_format = ['  %d', '  %d', '  ']
  let g:ale_linters = {
        \ 'go': [ 'vet', 'golint'],
        \ 'typescript': [ 'tslint', 'tsserver' ],
        \ }
  let g:ale_sh_shellcheck_options = '-x'
'''
# }}}

# vim-script {{{
[[plugins]]
repo = 'vim-scripts/HiColors'

[[plugins]]
repo = 'vim-scripts/applescript.vim'

[[plugins]]
repo = 'vim-scripts/autodate.vim'
if   = '''!has('kaoriya')'''

[[plugins]]
repo = 'vim-scripts/ingo-library'

[[plugins]]
repo = 'vim-scripts/nginx.vim'
# }}}

# dependencies {{{
[[plugins]]
repo = 'kana/vim-textobj-user'
# }}}

# vim:se fdm=marker:
