[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'SevereOverfl0w/deoplete-github'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'roxma/nvim-yarp'
if   = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if   = '''!has('nvim')'''
