[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'zchee/deoplete-jedi'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''
