# Shougoware {{{
[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim', 'vimfiler']

[[plugins]]
repo     = 'Shougo/unite.vim'
on_cmd   = ['Unite', 'UniteWithBufferDir', 'UniteWithCursorWord']
hook_add = '''"{{{
"  noremap zd :Unite dwm<CR>
"  noremap zD :Unite dein/log<CR>
"  noremap zf :Unite qfixhowm/new qfixhowm<CR>
"  noremap zF :Unite qfixhowm/new qfixhowm:nocache<CR>
"  noremap zg :Unite file_rec/async<CR>
"  noremap zG :Unite grep:.<CR>
"  "noremap <c-]> :UniteWithCursorWord -immediately tag/include<CR>
"  noremap zi :Unite tig<CR>
"  noremap zI :Unite gista<CR>
"  noremap zl :Unite outline<CR>
"  noremap zL :Unite decls<CR>
"  noremap zn :UniteWithBufferDir -buffer-name=files file file/new<CR>
"  noremap zu :Unite bundler<CR>
"  noremap zU :UniteResume<CR>
"  noremap zT :Unite tab<CR>
"  noremap zN :Unite -buffer-name=files file file/new<CR>
"  noremap zp :Unite dwm buffer_tab file_mru:long<CR>
"  noremap zP :Unite yankround<CR>
"  noremap zh :Unite ghq<CR>
"  noremap ZB :Unite rails/bundle<CR>
"  noremap ZC :Unite rails/controller<CR>
"  noremap ZD :Unite rails/db<CR>
"  noremap ZG :Unite rails/bundled_gem<CR>
"  noremap ZH :Unite rails/helper<CR>
"  noremap ZJ :Unite rails/javascript<CR>
"  noremap ZL :Unite rails/lib<CR>
"  noremap ZM :Unite rails/model<CR>
"  noremap ZO :Unite rails/command<CR>
"  noremap ZR :Unite rails/route<CR>
"  noremap ZS :Unite rails/spec<CR>
"  noremap ZT :Unite tsproject<CR>
"  noremap ZV :Unite rails/view<CR>
"  noremap Zc :Unite rails/config<CR>
"  noremap Zj :Unite rails/json_schema<CR>
"  noremap Zl :Unite rails/log<CR>
"  noremap Zm :Unite rails/mailer<CR>
"  noremap Zr :Unite rails/root<CR>
"  noremap Zs :Unite rails/stylesheet<CR>
"}}}'''
hook_source = 'call delphinus#init#unite#hook_source()'

[[plugins]]
repo      = 'Shougo/vimfiler'
on_source = ['unite.vim']
on_cmd    = [
  'VimFiler',
  'VimFilerExplorer',
  'Edit',
  'Read',
  'Source',
  'Write',
]
hook_add         = 'nnoremap `f :VimFilerBufferDir<CR>'
hook_source      = 'call delphinus#init#vimfiler#hook_source()'
hook_post_source = 'call delphinus#init#vimfiler#hook_post_source()'
# }}}

# for unite {{{
[[plugins]]
repo        = 'fuenor/qfixhowm'
on_map      = ['g,m', 'g,c', 'g,s', 'g,q']
on_source   = ['unite.vim']
hook_source = 'call delphinus#init#qfixhowm#hook_source()'

[[plugins]]
repo      = 'osyo-manga/unite-qfixhowm'
depends   = ['qfixhowm']
on_source = ['unite.vim']

[[plugins]]
repo      = 'delphinus/dwm.vim'
rev       = 'feature/disable-in-denite'
on_map    = ['<Plug>DWM']
on_source = ['unite.vim']
hook_add  = '''"{{{
  let g:delphinus#dwm#min_master_pane_width = get(g:, 'delphinus#dwm#min_master_pane_width', 86)

  let s:toggle_set_master_pane_width = 0

  let g:dwm_map_keys = 0
  nnoremap <C-J> <C-W>w
  nnoremap <C-K> <C-W>W
  nmap <C-S> <Plug>DWMRotateClockwise
  nmap <C-Q> <Plug>DWMRotateCounterclockwise
  nmap <C-N> <Plug>DWMNew
  nmap <C-C> <Plug>DWMClose
  nmap <C-Space> <Plug>DWMFocus
  nmap <C-L> <Plug>DWMGrowMaster

  command! DWMSetMasterPaneWidth call delphinus#dwm#set_master_pane_width()
  command! DWMDisable call delphinus#dwm#disable()
  command! DWMEnable call delphinus#dwm#enable()
"}}}'''

[[plugins]]
repo        = 'thinca/vim-ref'
on_cmd      = ['Ref']
on_source   = ['unite.vim']
hook_add    = '''"{{{
  noremap `rm :Unite ref/man<CR>
  noremap `rp :Unite ref/perldoc<CR>
  noremap `rr :Unite ref/refe<CR>
"}}}'''
hook_source = 'call delphinus#init#ref#hook_source()'
# }}}

# others {{{
[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_func  = ['tablemode#Toggle']
hook_add = '''
  nnoremap `tm :call tablemode#Toggle()<CR>
  let g:table_mode_corner='|'
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
on_func = ['vital#of']

[[plugins]]
repo = 'vim-scripts/visualrepeat'
# }}}

# vim:se fdm=marker:
