color = true
color-line-number = "1;32"
color-path = "1;34"
color-match = "1;33;47"
group = true
column = false
after = 0
before = 0
context = 0
files-with-matches = false
count = false
e = false
ignore-case = false
smart-case = true
word-regexp = false
ignore = "_worktree"
vcs-ignore = ".gitignore"
home-ptignore = "~/.ptignore"
skip-vcs-ignores = false
depth = 25
follow = false
hidden = false
