---
homebrew_packages_taps:
  - caskroom/cask
  - caskroom/versions
  - delphinus35/mosh
  - homebrew/binary
  - peco/peco
  - sanemat/font

homebrew_packages_packages:
  - { name: ag }
  - { name: brew-cask }
  - { name: coreutils }
  - { name: dtach }
  - { name: git }
  - { name: git-flow }
  - { name: htop-osx }
  - { name: ipcalc }
  - { name: jq }
  - { name: lftp }
  - { name: lua }
  - { name: lv }
  - { name: mysql }
  - { name: node }
  - { name: peco }
  - { name: perl-build }
  - { name: plenv }
  - { name: pt }
  - { name: pyenv }
  - { name: rbenv }
  - { name: reattach-to-user-namespace }
  - { name: ruby-build }
  - { name: ssh-copy-id }
  - { name: sshuttle }
  - { name: terminal-notifier }
  - { name: tig }
  - { name: tmux }
  - { name: vimpager }
  - { name: zpython }

homebrew_cask_packages_packages:
  - 1password
  - appcleaner
  - bartender
  - bettertouchtool
  - contexts
  - cyberduck
  - dropbox
  - firefox
  #- flash-player
  - flux
  - freemind
  - github
  - google-chrome
  - ibettercharge
  - iterm2
  - istat-menus
  - lastfm
  - mailbox
  - vlc

python2_version: 2.7.9
python3_version: 3.4.2
ruby_version: 2.1.3
perl_version: 5.20.1
home_dir: "{{ ansible_env['HOME'] }}"
cache_dir: "{{ home_dir }}/Library/Caches/Ansible"
fonts_dir: "{{ home_dir }}/Library/Fonts"
dotfiles_dir:         "{{ home_dir }}/git/dotfiles"
dotfiles_repo:        git://git.remora.cx/delphinus/dotfiles
dotfiles_repo_push:   git@git.remora.cx:delphinus/dotfiles
dotfiles_repo_github: git@github.com:delphinus35/dotfiles
