---
homebrew_packages_taps:
  - caskroom/cask
  - caskroom/versions
  - delphinus35/mosh
  - homebrew/binary
  - peco/peco
  - sanemat/font

homebrew_packages_packages:
  - { name: ag }
  - { name: brew-cask }
  - { name: coreutils }
  - { name: dtach }
  - { name: git }
  - { name: git-flow }
  - { name: htop-osx }
  - { name: ipcalc }
  - { name: jq }
  - { name: lftp }
  - { name: lua }
  - { name: lv }
  - { name: mysql }
  - { name: node }
  - { name: peco }
  - { name: perl-build }
  - { name: plenv }
  - { name: pstree }
  - { name: pt }
  - { name: pyenv }
  - { name: rbenv }
  - { name: reattach-to-user-namespace }
  - { name: ruby-build }
  - { name: ssh-copy-id }
  - { name: sshuttle }
  - { name: terminal-notifier }
  - { name: tig }
  - { name: tmux }
  - { name: vimpager }
  - { name: z }

  # for powerline
  - { name: automake }
  - { name: libgit2 }
  - { name: libtool }
  - { name: libuv }
  - { name: zpython }

homebrew_cask_packages_packages:
  - 1password
  - appcleaner
  - bartender
  - bettertouchtool
  - contexts
  - cyberduck
  - dropbox
  - firefox
  #- flash-player
  - flux
  - freemind
  - github
  - google-chrome
  - ibettercharge
  - iterm2
  - istat-menus
  - lastfm
  - mailbox
  - vlc

ruby_version: 2.2.2
perl_version: 5.22.0
home_dir: "{{ secret_home_dir }}"
cache_dir: "{{ home_dir }}/Library/Caches/Ansible"
fonts_dir: "{{ home_dir }}/Library/Fonts"
dotfiles_dir:         "{{ home_dir }}/git/dotfiles"
dotfiles_repo:        git@git.remora.cx:delphinus/dotfiles
dotfiles_repo_github: git@github.com:delphinus35/dotfiles
python_modules:
  - psutil
  - pyuv
  - vim-vint
  - git+https://github.com/powerline/powerline
  - git+https://github.com/delphinus35/powerlinex-segment-rbenv
  - git+https://github.com/omega/powerlinex-segment-plenv
python_modules_with_compiling:
  - pygit2
