---
- name: symlink keymap for AquaSKK
  file: >-
    src={{ dotfiles_dir }}/.config/AquaSKK/keymap.conf
    dest='~/Library/Application Support/AquaSKK/keymap.conf'
    state=link
    force=yes

- name: symlink kana-rule for AquaSKK
  file: >-
    src={{ dotfiles_dir }}/.config/AquaSKK/kana-rule.conf
    dest='~/Library/Application Support/AquaSKK/kana-rule.conf'
    state=link
    force=yes

- git: >-
    repo=https://{{ item }}
    dest=~/git/{{ item }}
  with_items:
    - github.com/KeenS/SKK_JISYO.wiktionary
    - github.com/uasi/skk-emoji-jisyo
    - github.com/ymrl/SKK-JISYO.emoji-ja

- homebrew: >-
    name=skktools
    state=latest

- name: remove the old dictionary
  file: >-
    path="~/Library/Application Support/AquaSKK/SKK_JISYO.shikakugoma"
    state=absent

- name: generate dictionary for shikakugoma
  shell: skkdic-expr SKK_JISYO.shikakugoma | skkdic-sort > ~/Library/Application\ Support/AquaSKK/SKK_JISYO.shikakugoma
  args:
    executable: /bin/bash
    chdir: ~/git/github.com/KeenS/SKK_JISYO.wiktionary

- name: copy emoji dictionary
  file: >-
    src=~/git/github.com/uasi/skk-emoji-jisyo/SKK-JISYO.emoji.utf8
    dest='~/Library/Application Support/AquaSKK/SKK_JISYO.emoji.utf8'
    state=link
    force=yes

- name: copy emoji-ja dictionary
  file: >-
    src=~/git/github.com/ymrl/SKK-JISYO.emoji-ja/SKK-JISYO.emoji-ja.utf8
    dest='~/Library/Application Support/AquaSKK/SKK_JISYO.emoji-ja.utf8'
    state=link
    force=yes
