---
- file: path=~/git state=directory

#- git:  repo=git@git.remora.cx:delphinus/dotfiles dest=~/git/dotfiles
#when: ansible_domain == 'local'

- command: git submodule update --init chdir=~/git/dotfiles
  register: submodules_update
  changed_when: submodules_update.stdout != ''

- file: path=~/.config state=directory
- file: src=~/git/dotfiles/{{ item }} dest=~/{{ item }} state=link force=yes
  with_items:
    - .config/ipython
    - .config/peco
    - .config/powerline
    - .editrc
    - .gitconfig
    - .inputrc
    - .jshintrc
    - .vim
    - .zprofile
    - .zshrc

- file: path='~/Library/Application Support/Karabiner' state=directory
- copy: src=files/private.xml dest='~/Library/Application Support/Karabiner/private.xml'
