---
- file: path={{ dotfiles_dir | dirname }} state=directory

- command: git remote -v chdir={{ dotfiles_dir }}
  register: remote_stat
  changed_when: remote_stat.rc not in [0, 1]

- command: git remote add github {{ dotfiles_repo_github }} chdir={{ dotfiles_dir }}
  when: remote_stat.stdout.find(dotfiles_repo_github) == -1

- file: path=~/.config state=directory
- file: src={{ '/'.join([dotfiles_dir, item]) }} dest=~/{{ item }} state=link force=yes
  with_items:
    - .config/ipython
    - .config/peco
    - .config/powerline
    - .editrc
    - .gitconfig
    - .inputrc
    - .jshintrc
    - .vim
    - .zprofile
    - .zshrc

- file: path='~/Library/Application Support/Karabiner' state=directory
- copy: src=files/private.xml dest='~/Library/Application Support/Karabiner/private.xml'

- file: path=~/.ssh/config state=touch
- lineinfile: dest=~/.ssh/config line='Host *' state=present
- lineinfile: dest=~/.ssh/config line='  ServerAliveInterval 120' insertafter='^Host \*$'
