---
- name: prepare config dir
  file: path={{ home_dir }}/.config/vifm/colors state=directory

- name: prepare ptpython config dir
  file: path={{ home_dir }}/.ptpython state=directory

- name: make dotfiles symlink
  file: src={{ '/'.join([dotfiles_dir, item]) }} dest={{ home_dir }}/{{ item }} state=link force=yes
  with_items:
    - .config/gocode
    - .config/ipython
    - .config/peco
    - .config/powerline
    - .config/ranger
    - .config/vifm/vifmrc
    - .config/vifm/colors/nord.vifm
    - .editrc
    - .gitconfig
    - .grcat
    - .inputrc
    - .jshintrc
    - .proverc
    - .ptconfig.toml
    - .ptpython/config.py
    - .tern-project
    - .tmux
    - .tmux.conf
    - .vim
    - .vimrc_first.vim
    - .zlogin
    - .zlogout
    - .zprezto
    - .zpreztorc
    - .zprofile
    - .zshenv
    - .zshrc

- name: make directory for Neovim
  file: dest={{ home_dir }}/.config/nvim state=directory

- name: make init.vim for Neovim
  file: src={{ dotfiles_dir }}/.vim/vimrc dest={{ home_dir }}/.config/nvim/init.vim state=link force=yes

  #- name: set config for kitty
  #file: src={{ dotfiles_dir }}/kitty.conf dest={{ home_dir }}/Library/Preferences/kitty/kitty.conf state=link force=yes
  #when: ansible_system == 'Darwin'

- name: symlink dircolors
  file: >-
    src={{ '/'.join([dotfiles_dir, 'submodules/nord-dircolors/src/dir_colors']) }}
    dest={{ home_dir }}/.dir_colors
    state=link
    force=yes

- name: create karabiner directory
  file: path='{{ home_dir }}/.config/karabiner/assets/complex_modifications' state=directory
  when: ansible_system == 'Darwin'
- name: create karabiner setting
  copy: src={{ item }}.json dest='{{ home_dir }}/.config/karabiner/assets/complex_modifications/{{ item }}.json'
  when: ansible_system == 'Darwin'
  with_items:
    - spreadsheets
    - escape
    - tab
    - edgeview2
    - slack
    - return_or_enter
    - tmux
    - contexts
    - excel
    - japanese
    - emacs

- file: path={{ home_dir }}/.ssh/config state=touch mode=0600
  changed_when: false
- lineinfile: dest={{ home_dir }}/.ssh/config line='Host *' state=present
- lineinfile: dest={{ home_dir }}/.ssh/config line='  ServerAliveInterval 120' insertafter='^Host \*$'

- git: >-
    repo=https://{{ item }}
    dest={{ home_dir }}/.go/src/{{ item }}
  with_items:
    - github.com/takaaki-kasai/git-foresta
  register: git_sync

- file: path={{ home_dir }}/.ghg/bin state=directory
  when: git_sync.changed

- name: copy git-foresta executable
  shell: cp {{ home_dir }}/{.go/src/github.com/takaaki-kasai/git-foresta,.ghg/bin}/git-foresta
  when: git_sync.changed

- file: path={{ home_dir }}/.ghg/bin/git-foresta mode=0755
  when: git_sync.changed
