---
- file: path={{ home_dir }}/.config state=directory

- name: make dotfiles symlink
  file: src={{ '/'.join([dotfiles_dir, item]) }} dest={{ home_dir }}/{{ item }} state=link force=yes
  with_items:
    - .config/gocode
    - .config/ipython
    - .config/peco
    - .config/powerline
    - .config/ranger
    - .editrc
    - .gitconfig
    - .grcat
    - .inputrc
    - .jshintrc
    - .myclirc
    - .proverc
    - .ptconfig.toml
    - .tern-project
    - .tmux
    - .tmux.conf
    - .vim
    - .vimrc_first.vim
    - .zlogin
    - .zlogout
    - .zprezto
    - .zpreztorc
    - .zprofile
    - .zshenv
    - .zshrc

- name: symlink dircolors
  file: >-
    src={{ '/'.join([dotfiles_dir, 'submodules/dircolors-solarized/dircolors.ansi-light']) }}
    dest={{ home_dir }}/.dir_colors
    state=link
    force=yes

- file: path='{{ home_dir }}/Library/Application Support/Karabiner' state=directory
  when: ansible_system == 'Darwin'
- copy: src=private.xml dest='{{ home_dir }}/Library/Application Support/Karabiner/private.xml'
  when: ansible_system == 'Darwin'

- file: path={{ home_dir }}/.ssh/config state=touch
  changed_when: false
- lineinfile: dest={{ home_dir }}/.ssh/config line='Host *' state=present
- lineinfile: dest={{ home_dir }}/.ssh/config line='  ServerAliveInterval 120' insertafter='^Host \*$'
