---
- name:          other homebrew packages
  homebrew:      name={{ item }} state=latest
  with_items:    other_homebrew_packages

- name:          other homebrew cask packages
  homebrew_cask: name={{ item }} state=installed
  with_items:    other_homebrew_cask_packages

- copy: src=files/macvim-kaoriya.rb dest=/usr/local/Library/Taps/caskroom/homebrew-versions/Casks/macvim-kaoriya.rb
- copy: src=files/symlinked.rb dest=/usr/local/Library/Taps/caskroom/homebrew-cask/lib/hbc/artifact/symlinked.rb

- command: brew cask info macvim-kaoriya
  register: macvim_kaoriya_info

- command: brew cask install macvim-kaoriya --override-system-vim
  when: macvim_kaoriya_info.stdout.find('Not installed') > -1
