---
- name:          other homebrew packages
  homebrew:      name={{ item }} state=latest
  with_items:    other_homebrew_packages

- name:          other homebrew cask packages
  homebrew_cask: name={{ item }} state=installed
  with_items:    other_homebrew_cask_packages

- name: determine brew-cask path
  shell: brew info brew-cask | perl -pe '($_) = /^(.*) \(.*?\) \*$/m'
  register: brew_cask_path

- patch: >
    src=files/symlinked.rb.patch
    basedir={{ brew_cask_path.stdout }}
    remote_src=yes
    strip=1

- name: copy macvim-kaoirya cask
  copy: >
    src=files/macvim-kaoriya.rb
    dest=/usr/local/Library/Taps/caskroom/homebrew-versions/Casks/macvim-kaoriya.rb

- command: brew cask info macvim-kaoriya
  register: macvim_kaoriya_info
  changed_when: macvim_kaoriya_info.rc != 0

- command: brew cask install macvim-kaoriya --override-system-vim
  when: macvim_kaoriya_info.stdout.find('Not installed') > -1

- homebrew_cask: name=firefoxdeveloperedition-ja state=installed
- homebrew_cask: name=karabiner state=installed
  sudo: yes
- homebrew_cask: name=keycastr state=installed
  sudo: yes
