---
- pip:
    name:
      - ansible-lint
      - neovim
      - neovim-remote
      - python-language-server
      - vint
      - yamllint
    executable: pip3
    extra_args: --user
    state: latest

# vim:se ft=yaml.ansible:
