---
- dnf:
    name: gcc, python36-devel, rpm-build
  become: true
  when: ansible_system == 'Linux' and ansible_distribution == 'CentOS'
- pip:
    name:
      - iterm2
      - neovim-remote
      - vint
    executable: pip3
    extra_args: --user
    state: latest

# vim:se ft=yaml.ansible:
