---
- pip:
    name:
      - Send2Trash
      - ansible-lint
      - git+https://github.com/will8211/unimatrix
      - neovim-remote
      - pynvim
      - python-language-server
      - vint
      - yamllint
    executable: pip3
    extra_args: --user
    state: latest

# vim:se ft=yaml.ansible:
