---
- name: make config for calling API
  copy:
    content: '{{ secret_office_api_config }}'
    dest: '{{ secret_office_api_config_file }}'

- name: remove config for calling API
  file: path='{{ secret_office_api_config }}' state=absent

- name: make repo setting
  template: >-
    src=organization_envrc.j2
    dest=~/git/{{ secret_office_organization }}/.envrc

- name: make repo vimrc
  template: >-
    src=organization_vimrc.j2
    dest=~/git/{{ secret_office_organization }}/.vimrc.local

- name: make dev envrc
  template: >-
    src=organization_envrc_go.j2
    dest=~/git/{{ secret_office_dev_envrc.repo }}/.envrc

- name: make dev envrc
  template: >-
    src=organization_vimrc_go.j2
    dest=~/git/{{ secret_office_dev_envrc.repo }}/.vimrc.local

- name: make ssh config
  template: >-
    src=ssh_config.j2
    dest=~/.ssh/config
