---
- name: make .config/powerline/config.json
  template: >-
    src=config_powerline_config_json.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/config.json

- name: make .config/powerline/themes/tmux/custom.json
  template: >-
    src=config_powerline_themes_tmux_custom.json.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/themes/tmux/custom.json

- name: make .git_prohibited_words
  template: >-
    src=git_prohibited_words.j2
    dest=~/.git_prohibited_words

- name: make .git_prohibited_words_checker_password
  template: >-
    src=git_prohibited_words_checker_password.j2
    dest=~/.git_prohibited_words_checker_password

- name: make .git/hooks/pre-commit
  template: >-
    src=git_hooks_pre-commit.j2
    dest={{ home_dir }}/git/dotfiles/.git/hooks/pre-commit
- file: path={{ home_dir }}/git/dotfiles/.git/hooks/pre-commit mode=0755

- name: make .homebrew_github_api_token
  template: >-
    src=homebrew_github_api_token.j2
    dest=~/.homebrew_github_api_token

- name: make .gitconfig_local
  template: >-
    src=gitconfig_local.j2
    dest={{ home_dir }}/.gitconfig_local

- name: make local_perl.py
  template: >-
    src=local_perl.py.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/ext/segments/local_perl.py

- name: local_perl.sh
  template: >-
    src=local_perl.sh.j2
    dest={{ home_dir }}/git/dotfiles/bin/local_perl.sh
  when: ansible_hostname == secret_office.hostnames[0]
- file: path={{ home_dir }}/git/dotfiles/bin/local_perl.sh mode=0755
  when: ansible_hostname == secret_office.hostnames[0]

- name: make .zshrc.local
  template: >-
    src=zshrc_local.j2
    dest={{ home_dir }}/.zshrc.local
  when: ansible_hostname in secret_office.hostnames

- name: make .vimrc-local
  template: >-
    src=vimrc_local.j2
    dest={{ home_dir }}/.vimrc-local

- name: make general .my.cnf
  template: >-
    src=my_cnf.j2
    dest=~/.my.cnf

- name: make .tsdrc
  template: >-
    src=tsdrc.j2
    dest=~/.tsdrc

- name: make taskd dir
  file: path={{ home_dir }}/.task state=directory

- name: make taskd files - private.certificate.pem
  copy:
    content: '{{ secret_taskd.private_certificate_pem }}'
    dest: '{{ secret_taskd.certificate }}'

- name: make taskd files - private.key.pem
  copy:
    content: '{{ secret_taskd.private_key_pem }}'
    dest: '{{ secret_taskd.key }}'

- name: make taskd files - ca.cert.pem
  copy:
    content: '{{ secret_taskd.ca_cert_pem }}'
    dest: '{{ secret_taskd.ca }}'

- name: make .taskrc
  template: >-
    src=taskrc.j2
    dest=~/.taskrc

- name: make memo directory
  file: path={{ home_dir }}/.config/memo state=directory

- name: make config for memo
  template: >-
    src=config_memo_toml.j2
    dest=~/.config/memo/config.toml

- name: make config for mycli
  template: >-
    src=myclirc.j2
    dest=~/.myclirc

- name: make setting for 3llo
  template: >-
    src=3llo.j2
    dest=~/.3llo
