---
- name: make .config/powerline/config.json
  template: >-
    src=config_powerline_config_json.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/config.json
- name: make .config/powerline/themes/tmux/custom.json
  template: >-
    src=config_powerline_themes_tmux_custom.json.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/themes/tmux/custom.json
- name: make .git_prohibited_words
  template: >-
    src=git_prohibited_words.j2
    dest=~/.git_prohibited_words
- name: make .git_prohibited_words_checker_password
  template: >-
    src=git_prohibited_words_checker_password.j2
    dest=~/.git_prohibited_words_checker_password
- name: make .git/hooks/pre-commit
  template: >-
    src=git_hooks_pre-commit.j2
    dest={{ home_dir }}/git/dotfiles/.git/hooks/pre-commit
- name: make .homebrew_github_api_token
  template: >-
    src=homebrew_github_api_token.j2
    dest=~/.homebrew_github_api_token
- name: make .gitconfig_local
  template: >-
    src=gitconfig_local.j2
    dest={{ home_dir }}/.gitconfig_local
- file: path={{ home_dir }}/git/dotfiles/.git/hooks/pre-commit mode=0755
- template: >-
    src=local_perl.py.j2
    dest={{ home_dir }}/git/dotfiles/.config/powerline/ext/segments/local_perl.py
- template: >-
    src=local_perl.sh.j2
    dest={{ home_dir }}/git/dotfiles/bin/local_perl.sh
  when: ansible_fqdn == secret_office.hostnames[0]
- file: path={{ home_dir }}/git/dotfiles/bin/local_perl.sh mode=0755
  when: ansible_fqdn == secret_office.hostnames[0]
- template: >-
    src=zshrc_local.j2
    dest={{ home_dir }}/.zshrc.local
  when: ansible_fqdn in secret_office.hostnames
- template: >-
    src=vimrc_local.j2
    dest={{ home_dir }}/.vimrc-local
