---
- name: make config for calling API
  copy:
    content: '{{ secret_office_api_config }}'
    dest: '{{ secret_office_api_config_file }}'

- name: make config for calling API on stage
  copy:
    content: '{{ secret_office_api_config_on_stage }}'
    dest: '{{ secret_office_api_config_file_on_stage }}'

- name: make config for calling API on prod live
  copy:
    content: '{{ secret_office_api_config_on_prod_live }}'
    dest: '{{ secret_office_api_config_file_on_prod_live }}'

- file: path=~/git/{{ secret_office_organization }} state=directory

- name: make repo setting
  template: >-
    src=organization_envrc.j2
    dest=~/git/{{ secret_office_organization }}/.envrc

- name: make repo vimrc
  template: >-
    src=organization_vimrc.j2
    dest=~/git/{{ secret_office_organization }}/.vimrc.local

- file: path=~/git/{{ secret_office_dev_envrc.repo }} state=directory

- name: make dev envrc
  template: >-
    src=organization_envrc_go.j2
    dest=~/git/{{ secret_office_dev_envrc.repo }}/.envrc

- name: make dev envrc
  template: >-
    src=organization_vimrc_go.j2
    dest=~/git/{{ secret_office_dev_envrc.repo }}/.vimrc.local

- name: make ssh config
  template: >-
    src=ssh_config.j2
    dest=~/.ssh/config
