---
- template: src=templates/config_powerline_config_json.j2 dest=~/git/dotfiles/.config/powerline/config.json
- template: src=templates/config_powerline_themes_tmux_custom.json.j2 dest=~/git/dotfiles/.config/powerline/themes/tmux/custom.json
- template: src=templates/git_prohibited_words.j2 dest=~/.git_prohibited_words
- template: src=templates/git_prohibited_words_checker_password.j2 dest=~/.git_prohibited_words_checker_password
- template: src=templates/git_hooks_pre-commit.j2 dest=~/git/dotfiles/.git/hooks/pre-commit
- template: src=templates/homebrew_github_api_token.j2 dest=~/.homebrew_github_api_token
- file: path=~/git/dotfiles/.git/hooks/pre-commit mode=0755
