---
- name: detect xterm-256color-italic terminfo
  shell: infocmp xterm-256color-italic
  register: term_st
  failed_when: term_st.rc not in [0, 1]
  changed_when: false

- template: >-
    src=xterm-256color-italic.terminfo.j2
    dest=/tmp/xterm-256color-italic.terminfo
  when: term_st.rc != 0

- command: tic /tmp/xterm-256color-italic.terminfo
  when: term_st.rc != 0

- file: path=/tmp/xterm-256color-italic.terminfo state=absent
