---
- file: path={{ home_dir }}/.terminfo state=directory

- name: search customized xterm-256color terminfo
  shell: find {{ home_dir }}/.terminfo -name xterm-256color | grep .
  register: term_st
  failed_when: term_st.rc not in [0, 1]
  changed_when: false

- copy: src=xterm-256color.terminfo dest=/tmp/xterm-256color.terminfo
  when: term_st.rc != 0

- command: tic /tmp/xterm-256color.terminfo
  when: term_st.rc != 0

- file: path=/tmp/xterm-256color.terminfo state=absent
