---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/secrets.yml
    - include: tasks/terminfo.yml
    - include: tasks/pip.yml

# vim:se ft=yaml.ansible:
