---
- hosts: localhost
  gather_facts: yes
  sudo: no
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/secrets.yml
    - include: tasks/git.yml
      when: ansible_system == 'Darwin'
    - include: tasks/env.yml
    - include: tasks/terminfo.yml
