---
- hosts: all
  gather_facts: no
  sudo: no
  vars_files:
    - vars/secrets.yml

  pre_tasks:
    - file: path=~/.bashrc state=touch
    - file: path=~/.bash_profile state=touch

  roles:
    - role: dghubble.homebrew-role
      bash_shell: True
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
    - common

  tasks:
    - include: tasks/post_homebrew.yml
    - include: tasks/other_homebrew.yml
    - include: tasks/install.yml
    - include: tasks/env.yml
    - include: tasks/ricty.yml
    - include: tasks/dotfiles.yml
    - include: tasks/secrets.yml
