---
- hosts: all
  gather_facts: yes
  sudo: no
  vars_files:
    - vars/main.yml
    - vars/secrets.yml

  pre_tasks:
    - file: path=~/.bashrc state=touch
      changed_when: false
    - file: path=~/.bash_profile state=touch
      changed_when: false
    - file: path=/usr/local owner=root group=admin mode=g+rwx state=directory
      sudo: yes
    - file: path=/opt owner=root group=wheel state=directory
      sudo: yes
    - file: path=/opt/homebrew-cask owner={{ ansible_user_id }} group=staff state=directory
      sudo: yes

  roles:
    - role: dghubble.homebrew-role
      bash_shell: True
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages

  tasks:
    - include: tasks/common.yml
    - include: tasks/ricty.yml
    - include: tasks/post_homebrew.yml
    - include: tasks/other_homebrew.yml
    - include: tasks/install.yml
    - include: tasks/env.yml
    - include: tasks/dotfiles.yml
    - include: tasks/secrets.yml
