---
- hosts: all
  gather_facts: yes
  sudo: no
  vars_files:
    - vars/secrets.yml

  pre_tasks:
    - file: path=~/.bashrc state=touch
    - file: path=~/.bash_profile state=touch
    - file: path=/usr/local owner=root group=admin state=directory
      sudo: yes
    - file: path=/opt owner=root group=wheel state=directory
      sudo: yes
    - file: path=/opt/homebrew-cask owner={{ ansible_user_id }} group=staff state=directory
      sudo: yes

  roles:
    - role: dghubble.homebrew-role
      bash_shell: True
    - hnakamur.homebrew-packages
    - hnakamur.homebrew-cask-packages
    - common

  tasks:
    - include: tasks/post_homebrew.yml
    - include: tasks/other_homebrew.yml
    - include: tasks/env.yml
    - include: tasks/ricty.yml
    - include: tasks/dotfiles.yml
    - include: tasks/secrets.yml
    - command: brew info ricty
      register: ricty_info
      changed_when: ricty_info.rc != 0
    - include: tasks/install.yml
      when: ricty_info.stdout.find('Not installed') > -1
