[[plugins]]
repo       = 'Shougo/deol.nvim'
on_command = ['Deol']
hook_add   = '''"{{{
  let g:deol#enable_dir_changed = 0
  nnoremap <C-\><C-n> :<C-u>Deol -split<CR>
  nnoremap <BS><C-n> :<C-u>Deol -split<CR>
  tnoremap <BS><C-n> <C-\><C-n>
  function! s:new_deol() abort
    if exists('t:deol')
      tabnew
    endif
    Deol
  endfunction
  " map for terminal + dwm.vim
  function s:insertIfDeol() abort
    if &filetype ==# 'deol'
      startinsert
    endif
  endfunction
  if has('nvim')
    tmap À <C-\><C-n><C-@>:<C-u>call <SID>insertIfDeol()<CR>
    tmap ã <C-\><C-n><C-c>
    tmap ê <C-\><C-n><C-j>
    tmap ë <C-\><C-n><C-k>
    tmap ï <C-\><C-n><C-w>oi
    tmap î <C-\><C-n>:<C-u>call <SID>new_deol()<CR>
    tmap ñ <C-\><C-n><C-q>:<C-u>call <SID>insertIfDeol()<CR>
    tmap ó <C-\><C-n><C-s>:<C-u>call <SID>insertIfDeol()<CR>
    tmap   <C-\><C-n><C-@>:<C-u>call <SID>insertIfDeol()<CR>
    tmap ú <C-\><C-n>z
    tmap » <C-\><C-n>:
    tnoremap <expr> ò '<C-\><C-N>"'.nr2char(getchar()).'pi'
    nmap À <C-@>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ã <C-c>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ê <C-j>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ë <C-k>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ï <C-w>o
    nmap î :<C-u>call <SID>new_deol()<CR>
    nmap ñ <C-q>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ó <C-s>:<C-u>call <SID>insertIfDeol()<CR>
    nmap   <C-@>:<C-u>call <SID>insertIfDeol()<CR>
    nmap ú z
    nmap » :
  else
    tmap <A-@> <C-\><C-n><C-@>:<C-u>call <SID>insertIfDeol()<CR>
    tmap <A-c> <C-\><C-n><C-c>
    tmap <A-j> <C-\><C-n><C-j>
    tmap <A-k> <C-\><C-n><C-k>
    tmap <A-o> <C-\><C-n><C-w>oi
    tmap <A-n> <C-\><C-n>:<C-u>call <SID>new_deol()<CR>
    tmap <A-q> <C-\><C-n><C-q>:<C-u>call <SID>insertIfDeol()<CR>
    tmap <A-s> <C-\><C-n><C-s>:<C-u>call <SID>insertIfDeol()<CR>
    tmap <A-Space> <C-\><C-n><C-@>:<C-u>call <SID>insertIfDeol()<CR>
    tmap <A-z> <C-\><C-n>z
    tmap <A-;> <C-\><C-n>:
    tmap <expr> <C-r> '<C-\><C-n>"'.nr2char(getchar()).'pi'
    nmap <A-@> <C-@>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-c> <C-c>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-j> <C-j>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-k> <C-k>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-o> <C-w>o
    nmap <A-n> :<C-u>call <SID>new_deol()<CR>
    nmap <A-q> <C-q>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-s> <C-s>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-Space> <C-@>:<C-u>call <SID>insertIfDeol()<CR>
    nmap <A-z> z
    namp <A-;> :
  endif
"}}}'''

[[plugins]]
repo   = 'fuenor/JpFormat.vim'
on_cmd = ['JpFormatAll', 'JpJoinAll']

[[plugins]]
repo     = 'lambdalisue/vim-gista'
on_cmd   = ['Gista']
on_func  = ['gista#']
hook_add = '''
  let g:gista#command#list#enable_default_mappings = 0
  nnoremap gl :<c-u>Gista list<CR>
  nnoremap gL :<c-u>Gista list 
'''
hook_post_source = 'call delphinus#init#gista#hook_post_source()'

[[plugins]]
repo     = 'lambdalisue/lista.nvim'
depends  = ['vim-rplugin']
on_cmd   = ['Lista', 'ListaCursorWord']
hook_source = '''
  let g:lista#custom_mappings = [
    \ ['<C-D>', '<Del>'],
    \ ['<C-A>', '<Home>'],
    \ ['<C-E>', '<End>'],
    \ ['<C-F>', '<Right>'],
    \ ['<C-B>', '<Left>'],
    \ ['<C-K>', '<lista:select_previous_candidate>'],
    \ ['<C-J>', '<lista:select_next_candidate>'],
    \ ['<C-C>', '<Esc>'],
    \]
'''
hook_add = '''
  nnoremap # :<C-u>Lista<CR>
  nnoremap g# :<C-u>ListaCursorWord<CR>
'''

[[plugins]]
repo   = 'powerman/vim-plugin-AnsiEsc'
on_cmd = ['AnsiEsc']

[[plugins]]
repo   = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo        = 'thinca/vim-fontzoom'
on_cmd      = ['Fontzoom']
on_map      = ['<Plug>(fontzoom-']
if          = '''has('gui')'''
hook_add    = '''"{{{
  nmap <unique> <silent> + <Plug>(fontzoom-larger)
  nmap <unique> <silent> - <Plug>(fontzoom-smaller)
  nmap <unique> <silent> <C-ScrollWheelUp> <Plug>(fontzoom-larger)
  nmap <unique> <silent> <C-ScrollWheelDown> <Plug>(fontzoom-smaller)
"}}}'''
hook_source = '''"{{{
  let g:fontzoom_no_default_key_mappings=1
"}}}'''

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']
on_source = ['capture.vim']

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]]
repo     = 'tyru/open-browser.vim'
on_cmd   = ['OpenBrowser', 'OpenBrowserSearch']
on_func  = ['openbrowser#open']
on_map   = ['<Plug>(openbrowser-']
hook_add = '''
  nmap g<CR> <Plug>(openbrowser-smart-search)
  vmap g<CR> <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo   = 'tweekmonster/startuptime.vim'
on_cmd = ['StartupTime']

[[plugins]]
repo   = 'vifm/vifm.vim'
on_cmd = ['EditVifm', 'VsplitVifm', 'SplitVifm', 'DiffVifm', 'TabVifm']
on_ft  = ['vifm']

# vim:se fdm=marker:
