[[plugins]]
repo   = 'fuenor/JpFormat.vim'
on_cmd = ['JpFormatAll', 'JpJoinAll']

[[plugins]]
repo     = 'lambdalisue/vim-gista'
on_cmd   = ['Gista']
on_func  = ['gista#']
hook_add = '''
  let g:gista#command#list#enable_default_mappings = 0
  nnoremap gl :<c-u>Gista list<CR>
  nnoremap gL :<c-u>Gista list 
'''
hook_post_source = 'call delphinus#init#gista#hook_post_source()'

[[plugins]]
repo     = 'lambdalisue/lista.nvim'
depends  = ['vim-rplugin']
on_cmd   = ['Lista', 'ListaCursorWord']
hook_source = '''
  let g:lista#custom_mappings = [
    \ ['<C-D>', '<Del>'],
    \ ['<C-A>', '<Home>'],
    \ ['<C-E>', '<End>'],
    \ ['<C-F>', '<Right>'],
    \ ['<C-B>', '<Left>'],
    \ ['<C-K>', '<lista:select_previous_candidate>'],
    \ ['<C-J>', '<lista:select_next_candidate>'],
    \ ['<C-C>', '<Esc>'],
    \]
'''
hook_add = '''
  nnoremap # :<C-u>Lista<CR>
  nnoremap g# :<C-u>ListaCursorWord<CR>
'''

[[plugins]]
repo   = 'powerman/vim-plugin-AnsiEsc'
on_cmd = ['AnsiEsc']

[[plugins]]
repo   = 'sjl/gundo.vim'
on_cmd = ['GundoToggle']

[[plugins]]
repo        = 'thinca/vim-fontzoom'
on_cmd      = ['Fontzoom']
on_map      = ['<Plug>(fontzoom-']
if          = '''has('gui')'''
hook_add    = '''"{{{
  nmap <unique> <silent> + <Plug>(fontzoom-larger)
  nmap <unique> <silent> - <Plug>(fontzoom-smaller)
  nmap <unique> <silent> <C-ScrollWheelUp> <Plug>(fontzoom-larger)
  nmap <unique> <silent> <C-ScrollWheelDown> <Plug>(fontzoom-smaller)
"}}}'''
hook_source = '''"{{{
  let g:fontzoom_no_default_key_mappings=1
"}}}'''

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']
on_source = ['capture.vim']

[[plugins]]
repo   = 'tyru/capture.vim'
on_cmd = ['Capture']

[[plugins]]
repo     = 'tyru/open-browser.vim'
on_cmd   = ['OpenBrowser', 'OpenBrowserSearch']
on_func  = ['openbrowser#open']
on_map   = ['<Plug>(openbrowser-']
hook_add = '''
  nmap g<CR> <Plug>(openbrowser-smart-search)
  vmap g<CR> <Plug>(openbrowser-smart-search)
'''

[[plugins]]
repo   = 'tweekmonster/startuptime.vim'
on_cmd = ['StartupTime']

[[plugins]]
repo   = 'vifm/vifm.vim'
on_cmd = ['EditVifm', 'VsplitVifm', 'SplitVifm', 'DiffVifm', 'TabVifm']
on_ft  = ['vifm']
