[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = ['InsertEnter']
depends     = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = ''' "{{{
  let g:deoplete#enable_at_startup = 1
  call deoplete#initialize()
  call deoplete#custom#source('_', 'converters', [
        \ 'converter_auto_paren',
        \ 'converter_remove_overlap',
        \ 'converter_truncate_abbr',
        \ 'converter_truncate_menu',
        \ ])
  call deoplete#custom#source('look', 'rank', 0)
  inoremap <silent> <expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
  inoremap <silent> <expr> <S-TAB>
        \ pumvisible() ? "\<C-p>" :
        \ <SID>check_back_space() ? "\<S-TAB>" :
        \ deoplete#manual_complete()
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~# '\s'
  endfunction
"}}} '''
hook_post_update = '!pip3 install -U --user neovim'

[[plugins]]
repo      = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neopairs.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/echodoc.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo        = 'autozimu/LanguageClient-neovim'
rev         = 'next'
on_ft       = ['python', 'ruby', 'vue'] # for mappings
on_source   = ['deoplete.nvim']
hook_add = '''
  let g:LanguageClient_serverCommands = {
        \ 'go': ['golsp'],
        \ 'python': ['pyls'],
        \ 'ruby': ['solargraph', 'stdio'],
        \ 'vue': ['vls'],
        \ }
  " vim-go is used for mappings in go
  augroup LanguageClient
    autocmd!
    autocmd FileType python,ruby,vue nnoremap <buffer> <silent> K :call LanguageClient#textDocument_hover()<CR>
    autocmd FileType python,ruby,vue nnoremap <buffer> <silent> gd :call LanguageClient#textDocument_definition()<CR>
    autocmd FileType python,ruby,vue nnoremap <buffer> <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
  augroup END
'''
hook_post_update = '''
  !bash install.sh
  !npm install -g vue-language-server
  !pip3 install -U --user python-language-server
  !gem install --user-install solargraph
  !go get -u golang.org/x/tools/cmd/golsp
'''

[[plugins]]
repo     = 'mhartington/nvim-typescript'
on_ft    = ['typescript']
hook_add = '''
  let g:nvim_typescript#default_mappings = 1
  let g:nvim_typescript#diagnostics_enable = 0
'''
hook_post_update = '''
  !sh ./install.sh
'''

[plugins.ftplugin]
typescript = 'nnoremap <buffer> <silent> <C-w><C-]> :split \| TSTypeDef<CR>'

[[plugins]]
repo  = 'Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo    = 'carlitux/deoplete-ternjs'
on_ft   = ['javascript']
hook_post_update = '''
  !npm install -g tern
'''
hook_source = '''
  let g:deoplete#sources#ternjs#types = 1
  let g:deoplete#sources#ternjs#depths = 1
  let g:deoplete#sources#ternjs#docs = 1
'''

[[plugins]]
repo      = 'wellle/tmux-complete.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim']
