[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_event    = ['InsertEnter']
depends     = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = '''
"{{{
  let g:deoplete#enable_at_startup = 1
  call deoplete#initialize()
  call deoplete#custom#source('_', 'converters', [
        \ 'converter_auto_paren',
        \ 'converter_remove_overlap',
        \ 'converter_truncate_abbr',
        \ 'converter_truncate_menu',
        \ ])
  call deoplete#custom#source('look', 'rank', 0)
  inoremap <silent> <expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ deoplete#manual_complete()
  inoremap <silent> <expr> <S-TAB>
        \ pumvisible() ? "\<C-p>" :
        \ <SID>check_back_space() ? "\<S-TAB>" :
        \ deoplete#manual_complete()
  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1] =~# '\s'
  endfunction
"}}}
'''
hook_post_update = '!pip3 install -U --user neovim'

[[plugins]]
repo      = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neopairs.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/echodoc.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo        = 'autozimu/LanguageClient-neovim'
rev         = 'next'
on_source   = ['deoplete.nvim']
hook_source = '''
  let g:LanguageClient_serverCommands = {
        \ 'vue': ['vls'],
        \ }
'''
hook_post_update = '''
  !bash install.sh
  !npm install -g vue-language-server
'''

[[plugins]]
repo     = 'mhartington/nvim-typescript'
on_ft    = ['typescript']
hook_add = '''
  let g:nvim_typescript#default_mappings = 1
  let g:nvim_typescript#diagnostics_enable = 0
'''
hook_post_update = '''
  !sh ./install.sh
'''

[[plugins]]
repo             = 'zchee/deoplete-go'
on_ft            = ['go']
hook_post_update = '!make'

[[plugins]]
repo    = 'zchee/deoplete-jedi'
on_ft   = ['python']
depends = ['jedi-vim']

[[plugins]]
repo  = 'Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo    = 'carlitux/deoplete-ternjs'
on_ft   = ['javascript']
hook_post_update = '''
  !npm install -g tern
'''
hook_source = '''
  let g:deoplete#sources#ternjs#types = 1
  let g:deoplete#sources#ternjs#depths = 1
  let g:deoplete#sources#ternjs#docs = 1
'''

[[plugins]]
repo      = 'wellle/tmux-complete.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim']
