[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo    = 'zchee/deoplete-jedi'
depends = ['jedi-vim']

[[plugins]]
repo = 'SevereOverfl0w/deoplete-github'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo     = 'mhartington/nvim-typescript'
hook_add = '''
  let g:nvim_typescript#type_info_on_hold = 1
  let g:nvim_typescript#default_mappings = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'
hook_source = '''
  " Set path for python3 for python36u packages in CentOS7
  if !executable('python3') && executable('python3.6')
    let g:python3_host_prog = exepath('python3.6')
  endif
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo     = 'ujihisa/neco-look'
