[[plugins]]
repo        = 'Shougo/deoplete.nvim'
on_i        = 1
depends     = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#omni#input_patterns = get(g:, 'deoplete#omni#input_patterns', {})
  let g:deoplete#omni#input_patterns.typescript = '[^. \t]\.(?:[a-zA-Z_]\w*)?'
  let g:deoplete#omni#functions = get(g:, 'deoplete#omni#functions', {})
  let g:deoplete#omni#functions.typescript = 'tsuquyomi#complete'
  call deoplete#initialize()
  call deoplete#custom#source('_', 'converters', [
        \ 'converter_auto_paren',
        \ 'converter_remove_overlap',
        \ 'converter_truncate_abbr',
        \ 'converter_truncate_menu',
        \ ])
'''
hook_post_update = '!pip3 install -U --user neovim'

[[plugins]]
repo      = 'Shougo/neoinclude.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neopairs.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/echodoc.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo             = 'zchee/deoplete-go'
on_ft            = ['go']
hook_post_update = 'make'

[[plugins]]
repo  = 'Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo    = 'carlitux/deoplete-ternjs'
depends = ['tern_for_vim']
on_ft   = ['javascript']

[[plugins]]
repo      = 'wellle/tmux-complete.vim'
on_source = ['deoplete.nvim']

[[plugins]]
repo      = 'Shougo/neco-syntax'
on_source = ['deoplete.nvim']
