[[plugins]]
repo = 'zchee/deoplete-zsh'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'

[[plugins]]
repo = 'roxma/nvim-yarp'
hook_source = '''
  " Set path for python3 for python37u packages in CentOS7
  if !executable('python3') && executable('python3.7')
    let g:python3_host_prog = exepath('python3.7')
  endif
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo     = 'ujihisa/neco-look'
