[[plugins]]
repo      = 'delphinus/dwm.vim'
rev       = 'feature/disable-in-denite'
on_map    = ['<Plug>DWM']
on_source = ['unite.vim']
hook_add  = '''"{{{
  let g:delphinus#dwm#min_master_pane_width = get(g:, 'delphinus#dwm#min_master_pane_width', 86)

  let s:toggle_set_master_pane_width = 0

  let g:dwm_map_keys = 0
  nnoremap <C-J> <C-W>w
  nnoremap <C-K> <C-W>W
  nmap <C-S> <Plug>DWMRotateClockwise
  nmap <C-Q> <Plug>DWMRotateCounterclockwise
  nmap <C-N> <Plug>DWMNew
  nmap <C-C> <Plug>DWMClose
  nmap <C-Space> <Plug>DWMFocus
  nmap <C-@> <Plug>DWMFocus
  nmap <C-L> <Plug>DWMGrowMaster

  command! DWMSetMasterPaneWidth call delphinus#dwm#set_master_pane_width()
  command! DWMDisable call delphinus#dwm#disable()
  command! DWMEnable call delphinus#dwm#enable()
"}}}'''

[[plugins]]
repo     = 'dhruvasagar/vim-table-mode'
on_func  = ['tablemode#Toggle']
hook_add = '''
  nnoremap `tm :call tablemode#Toggle()<CR>
  let g:table_mode_corner='|'
'''

[[plugins]]
repo = 'vim-jp/vital.vim'
on_func = ['vital#of']

[[plugins]]
repo = 'vim-scripts/visualrepeat'

# vim:se fdm=marker:
