[[plugins]]
repo     = 'Shougo/unite.vim'
on_cmd   = ['Unite', 'UniteWithBufferDir', 'UniteWithCursorWord']
hook_add = '''"{{{
"  noremap zd :Unite dwm<CR>
"  noremap zD :Unite dein/log<CR>
"  noremap zf :Unite qfixhowm/new qfixhowm<CR>
"  noremap zF :Unite qfixhowm/new qfixhowm:nocache<CR>
"  noremap zg :Unite file_rec/async<CR>
"  noremap zG :Unite grep:.<CR>
"  "noremap <c-]> :UniteWithCursorWord -immediately tag/include<CR>
"  noremap zi :Unite tig<CR>
"  noremap zI :Unite gista<CR>
"  noremap zl :Unite outline<CR>
"  noremap zL :Unite decls<CR>
"  noremap zn :UniteWithBufferDir -buffer-name=files file file/new<CR>
"  noremap zu :Unite bundler<CR>
"  noremap zU :UniteResume<CR>
"  noremap zT :Unite tab<CR>
"  noremap zN :Unite -buffer-name=files file file/new<CR>
"  noremap zp :Unite dwm buffer_tab file_mru:long<CR>
"  noremap zP :Unite yankround<CR>
"  noremap zh :Unite ghq<CR>
"  noremap ZB :Unite rails/bundle<CR>
"  noremap ZC :Unite rails/controller<CR>
"  noremap ZD :Unite rails/db<CR>
"  noremap ZG :Unite rails/bundled_gem<CR>
"  noremap ZH :Unite rails/helper<CR>
"  noremap ZJ :Unite rails/javascript<CR>
"  noremap ZL :Unite rails/lib<CR>
"  noremap ZM :Unite rails/model<CR>
"  noremap ZO :Unite rails/command<CR>
"  noremap ZR :Unite rails/route<CR>
"  noremap ZS :Unite rails/spec<CR>
"  noremap ZT :Unite tsproject<CR>
"  noremap ZV :Unite rails/view<CR>
"  noremap Zc :Unite rails/config<CR>
"  noremap Zj :Unite rails/json_schema<CR>
"  noremap Zl :Unite rails/log<CR>
"  noremap Zm :Unite rails/mailer<CR>
"  noremap Zr :Unite rails/root<CR>
"  noremap Zs :Unite rails/stylesheet<CR>
"}}}'''
hook_source = 'call delphinus#init#unite#hook_source()'

[[plugins]]
repo        = 'thinca/vim-ref'
on_cmd      = ['Ref']
on_source   = ['unite.vim']
hook_add    = '''"{{{
  noremap `rm :Unite ref/man<CR>
  noremap `rp :Unite ref/perldoc<CR>
  noremap `rr :Unite ref/refe<CR>
"}}}'''
hook_source = 'call delphinus#init#ref#hook_source()'
