import = [
  "/Users/jinnouchi.yasushi/.config/alacritty/nord.toml",
  "/Users/jinnouchi.yasushi/.alacritty-env.toml"
]

[shell]
program = "/Users/jinnouchi.yasushi/git/dotfiles/bin/tmux-run"

[cursor.vi_mode_style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "SF Mono Square"
style = "Bold"

[font.bold_italic]
family = "SF Mono Square"
style = "Bold Italic"

[font.italic]
family = "SF Mono Square"
style = "Italic"

[font.normal]
family = "SF Mono Square"
style = "Regular"

[terminal]
osc52 = "CopyPaste"

[window]
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 2
